// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newAccessKey(db *gorm.DB, opts ...gen.DOOption) accessKey {
	_accessKey := accessKey{}

	_accessKey.accessKeyDo.UseDB(db, opts...)
	_accessKey.accessKeyDo.UseModel(&model.AccessKey{})

	tableName := _accessKey.accessKeyDo.TableName()
	_accessKey.ALL = field.NewAsterisk(tableName)
	_accessKey.ID = field.NewInt64(tableName, "id")
	_accessKey.UserID = field.NewInt64(tableName, "user_id")
	_accessKey.AccessKey = field.NewString(tableName, "access_key")
	_accessKey.SecretKey = field.NewString(tableName, "secret_key")
	_accessKey.Alias_ = field.NewString(tableName, "alias")
	_accessKey.Status = field.NewInt32(tableName, "status")
	_accessKey.Permission = field.NewString(tableName, "permission")
	_accessKey.LastUsedAt = field.NewTime(tableName, "last_used_at")
	_accessKey.ExpiresAt = field.NewTime(tableName, "expires_at")
	_accessKey.CreatedAt = field.NewTime(tableName, "created_at")
	_accessKey.UpdatedAt = field.NewTime(tableName, "updated_at")

	_accessKey.fillFieldMap()

	return _accessKey
}

// accessKey AccessKey 密钥表
type accessKey struct {
	accessKeyDo accessKeyDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	UserID     field.Int64  // 所属用户ID
	AccessKey  field.String // AK 公开标识
	SecretKey  field.String // SK 加密存储(AES)
	Alias_     field.String // 别名/备注
	Status     field.Int32  // 1=启用 0=禁用
	Permission field.String // 细粒度权限(NULL=全部)
	LastUsedAt field.Time   // 最后使用时间
	ExpiresAt  field.Time   // 过期时间(NULL=永不过期)
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (a accessKey) Table(newTableName string) *accessKey {
	a.accessKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accessKey) As(alias string) *accessKey {
	a.accessKeyDo.DO = *(a.accessKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accessKey) updateTableName(table string) *accessKey {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.UserID = field.NewInt64(table, "user_id")
	a.AccessKey = field.NewString(table, "access_key")
	a.SecretKey = field.NewString(table, "secret_key")
	a.Alias_ = field.NewString(table, "alias")
	a.Status = field.NewInt32(table, "status")
	a.Permission = field.NewString(table, "permission")
	a.LastUsedAt = field.NewTime(table, "last_used_at")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *accessKey) WithContext(ctx context.Context) *accessKeyDo {
	return a.accessKeyDo.WithContext(ctx)
}

func (a accessKey) TableName() string { return a.accessKeyDo.TableName() }

func (a accessKey) Alias() string { return a.accessKeyDo.Alias() }

func (a accessKey) Columns(cols ...field.Expr) gen.Columns { return a.accessKeyDo.Columns(cols...) }

func (a *accessKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accessKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["access_key"] = a.AccessKey
	a.fieldMap["secret_key"] = a.SecretKey
	a.fieldMap["alias"] = a.Alias_
	a.fieldMap["status"] = a.Status
	a.fieldMap["permission"] = a.Permission
	a.fieldMap["last_used_at"] = a.LastUsedAt
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a accessKey) clone(db *gorm.DB) accessKey {
	a.accessKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accessKey) replaceDB(db *gorm.DB) accessKey {
	a.accessKeyDo.ReplaceDB(db)
	return a
}

type accessKeyDo struct{ gen.DO }

func (a accessKeyDo) Debug() *accessKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a accessKeyDo) WithContext(ctx context.Context) *accessKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accessKeyDo) ReadDB() *accessKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a accessKeyDo) WriteDB() *accessKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a accessKeyDo) Session(config *gorm.Session) *accessKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a accessKeyDo) Clauses(conds ...clause.Expression) *accessKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accessKeyDo) Returning(value interface{}, columns ...string) *accessKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accessKeyDo) Not(conds ...gen.Condition) *accessKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accessKeyDo) Or(conds ...gen.Condition) *accessKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accessKeyDo) Select(conds ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accessKeyDo) Where(conds ...gen.Condition) *accessKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accessKeyDo) Order(conds ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accessKeyDo) Distinct(cols ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accessKeyDo) Omit(cols ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accessKeyDo) Join(table schema.Tabler, on ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accessKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accessKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accessKeyDo) Group(cols ...field.Expr) *accessKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accessKeyDo) Having(conds ...gen.Condition) *accessKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accessKeyDo) Limit(limit int) *accessKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accessKeyDo) Offset(offset int) *accessKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accessKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *accessKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accessKeyDo) Unscoped() *accessKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accessKeyDo) Create(values ...*model.AccessKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accessKeyDo) CreateInBatches(values []*model.AccessKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accessKeyDo) Save(values ...*model.AccessKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accessKeyDo) First() (*model.AccessKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessKey), nil
	}
}

func (a accessKeyDo) Take() (*model.AccessKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessKey), nil
	}
}

func (a accessKeyDo) Last() (*model.AccessKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessKey), nil
	}
}

func (a accessKeyDo) Find() ([]*model.AccessKey, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccessKey), err
}

func (a accessKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccessKey, err error) {
	buf := make([]*model.AccessKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accessKeyDo) FindInBatches(result *[]*model.AccessKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accessKeyDo) Attrs(attrs ...field.AssignExpr) *accessKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accessKeyDo) Assign(attrs ...field.AssignExpr) *accessKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accessKeyDo) Joins(fields ...field.RelationField) *accessKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accessKeyDo) Preload(fields ...field.RelationField) *accessKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accessKeyDo) FirstOrInit() (*model.AccessKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessKey), nil
	}
}

func (a accessKeyDo) FirstOrCreate() (*model.AccessKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessKey), nil
	}
}

func (a accessKeyDo) FindByPage(offset int, limit int) (result []*model.AccessKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accessKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accessKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accessKeyDo) Delete(models ...*model.AccessKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accessKeyDo) withDO(do gen.Dao) *accessKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
