// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newAsyncTask(db *gorm.DB, opts ...gen.DOOption) asyncTask {
	_asyncTask := asyncTask{}

	_asyncTask.asyncTaskDo.UseDB(db, opts...)
	_asyncTask.asyncTaskDo.UseModel(&model.AsyncTask{})

	tableName := _asyncTask.asyncTaskDo.TableName()
	_asyncTask.ALL = field.NewAsterisk(tableName)
	_asyncTask.ID = field.NewInt64(tableName, "id")
	_asyncTask.TaskID = field.NewString(tableName, "task_id")
	_asyncTask.TaskType = field.NewString(tableName, "task_type")
	_asyncTask.UploadID = field.NewString(tableName, "upload_id")
	_asyncTask.ObjectID = field.NewInt64(tableName, "object_id")
	_asyncTask.Status = field.NewInt32(tableName, "status")
	_asyncTask.Progress = field.NewInt32(tableName, "progress")
	_asyncTask.Result = field.NewString(tableName, "result")
	_asyncTask.ErrorMsg = field.NewString(tableName, "error_msg")
	_asyncTask.RetryCount = field.NewInt32(tableName, "retry_count")
	_asyncTask.MaxRetry = field.NewInt32(tableName, "max_retry")
	_asyncTask.WorkerID = field.NewString(tableName, "worker_id")
	_asyncTask.StartedAt = field.NewTime(tableName, "started_at")
	_asyncTask.FinishedAt = field.NewTime(tableName, "finished_at")
	_asyncTask.CreatedAt = field.NewTime(tableName, "created_at")
	_asyncTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_asyncTask.fillFieldMap()

	return _asyncTask
}

// asyncTask 异步任务表
type asyncTask struct {
	asyncTaskDo asyncTaskDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	TaskID     field.String // 任务唯一ID
	TaskType   field.String // PHYSICAL_MERGE/TRANSCODE/IMG_PROCESS
	UploadID   field.String // 关联分片会话ID
	ObjectID   field.Int64  // 关联对象ID
	Status     field.Int32  // 0=待执行 1=执行中 2=完成 3=失败
	Progress   field.Int32  // 进度 0~100
	Result     field.String // 执行结果
	ErrorMsg   field.String // 失败原因
	RetryCount field.Int32  // 已重试次数
	MaxRetry   field.Int32  // 最大重试次数
	WorkerID   field.String // 处理该任务的Worker标识
	StartedAt  field.Time   // 开始执行时间
	FinishedAt field.Time   // 完成时间
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (a asyncTask) Table(newTableName string) *asyncTask {
	a.asyncTaskDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a asyncTask) As(alias string) *asyncTask {
	a.asyncTaskDo.DO = *(a.asyncTaskDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *asyncTask) updateTableName(table string) *asyncTask {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.TaskID = field.NewString(table, "task_id")
	a.TaskType = field.NewString(table, "task_type")
	a.UploadID = field.NewString(table, "upload_id")
	a.ObjectID = field.NewInt64(table, "object_id")
	a.Status = field.NewInt32(table, "status")
	a.Progress = field.NewInt32(table, "progress")
	a.Result = field.NewString(table, "result")
	a.ErrorMsg = field.NewString(table, "error_msg")
	a.RetryCount = field.NewInt32(table, "retry_count")
	a.MaxRetry = field.NewInt32(table, "max_retry")
	a.WorkerID = field.NewString(table, "worker_id")
	a.StartedAt = field.NewTime(table, "started_at")
	a.FinishedAt = field.NewTime(table, "finished_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *asyncTask) WithContext(ctx context.Context) *asyncTaskDo {
	return a.asyncTaskDo.WithContext(ctx)
}

func (a asyncTask) TableName() string { return a.asyncTaskDo.TableName() }

func (a asyncTask) Alias() string { return a.asyncTaskDo.Alias() }

func (a asyncTask) Columns(cols ...field.Expr) gen.Columns { return a.asyncTaskDo.Columns(cols...) }

func (a *asyncTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *asyncTask) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 16)
	a.fieldMap["id"] = a.ID
	a.fieldMap["task_id"] = a.TaskID
	a.fieldMap["task_type"] = a.TaskType
	a.fieldMap["upload_id"] = a.UploadID
	a.fieldMap["object_id"] = a.ObjectID
	a.fieldMap["status"] = a.Status
	a.fieldMap["progress"] = a.Progress
	a.fieldMap["result"] = a.Result
	a.fieldMap["error_msg"] = a.ErrorMsg
	a.fieldMap["retry_count"] = a.RetryCount
	a.fieldMap["max_retry"] = a.MaxRetry
	a.fieldMap["worker_id"] = a.WorkerID
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["finished_at"] = a.FinishedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a asyncTask) clone(db *gorm.DB) asyncTask {
	a.asyncTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a asyncTask) replaceDB(db *gorm.DB) asyncTask {
	a.asyncTaskDo.ReplaceDB(db)
	return a
}

type asyncTaskDo struct{ gen.DO }

func (a asyncTaskDo) Debug() *asyncTaskDo {
	return a.withDO(a.DO.Debug())
}

func (a asyncTaskDo) WithContext(ctx context.Context) *asyncTaskDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a asyncTaskDo) ReadDB() *asyncTaskDo {
	return a.Clauses(dbresolver.Read)
}

func (a asyncTaskDo) WriteDB() *asyncTaskDo {
	return a.Clauses(dbresolver.Write)
}

func (a asyncTaskDo) Session(config *gorm.Session) *asyncTaskDo {
	return a.withDO(a.DO.Session(config))
}

func (a asyncTaskDo) Clauses(conds ...clause.Expression) *asyncTaskDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a asyncTaskDo) Returning(value interface{}, columns ...string) *asyncTaskDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a asyncTaskDo) Not(conds ...gen.Condition) *asyncTaskDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a asyncTaskDo) Or(conds ...gen.Condition) *asyncTaskDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a asyncTaskDo) Select(conds ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a asyncTaskDo) Where(conds ...gen.Condition) *asyncTaskDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a asyncTaskDo) Order(conds ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a asyncTaskDo) Distinct(cols ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a asyncTaskDo) Omit(cols ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a asyncTaskDo) Join(table schema.Tabler, on ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a asyncTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a asyncTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a asyncTaskDo) Group(cols ...field.Expr) *asyncTaskDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a asyncTaskDo) Having(conds ...gen.Condition) *asyncTaskDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a asyncTaskDo) Limit(limit int) *asyncTaskDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a asyncTaskDo) Offset(offset int) *asyncTaskDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a asyncTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *asyncTaskDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a asyncTaskDo) Unscoped() *asyncTaskDo {
	return a.withDO(a.DO.Unscoped())
}

func (a asyncTaskDo) Create(values ...*model.AsyncTask) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a asyncTaskDo) CreateInBatches(values []*model.AsyncTask, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a asyncTaskDo) Save(values ...*model.AsyncTask) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a asyncTaskDo) First() (*model.AsyncTask, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AsyncTask), nil
	}
}

func (a asyncTaskDo) Take() (*model.AsyncTask, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AsyncTask), nil
	}
}

func (a asyncTaskDo) Last() (*model.AsyncTask, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AsyncTask), nil
	}
}

func (a asyncTaskDo) Find() ([]*model.AsyncTask, error) {
	result, err := a.DO.Find()
	return result.([]*model.AsyncTask), err
}

func (a asyncTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AsyncTask, err error) {
	buf := make([]*model.AsyncTask, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a asyncTaskDo) FindInBatches(result *[]*model.AsyncTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a asyncTaskDo) Attrs(attrs ...field.AssignExpr) *asyncTaskDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a asyncTaskDo) Assign(attrs ...field.AssignExpr) *asyncTaskDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a asyncTaskDo) Joins(fields ...field.RelationField) *asyncTaskDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a asyncTaskDo) Preload(fields ...field.RelationField) *asyncTaskDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a asyncTaskDo) FirstOrInit() (*model.AsyncTask, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AsyncTask), nil
	}
}

func (a asyncTaskDo) FirstOrCreate() (*model.AsyncTask, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AsyncTask), nil
	}
}

func (a asyncTaskDo) FindByPage(offset int, limit int) (result []*model.AsyncTask, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a asyncTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a asyncTaskDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a asyncTaskDo) Delete(models ...*model.AsyncTask) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *asyncTaskDo) withDO(do gen.Dao) *asyncTaskDo {
	a.DO = *do.(*gen.DO)
	return a
}
