// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newBucketCorsRule(db *gorm.DB, opts ...gen.DOOption) bucketCorsRule {
	_bucketCorsRule := bucketCorsRule{}

	_bucketCorsRule.bucketCorsRuleDo.UseDB(db, opts...)
	_bucketCorsRule.bucketCorsRuleDo.UseModel(&model.BucketCorsRule{})

	tableName := _bucketCorsRule.bucketCorsRuleDo.TableName()
	_bucketCorsRule.ALL = field.NewAsterisk(tableName)
	_bucketCorsRule.ID = field.NewInt64(tableName, "id")
	_bucketCorsRule.UserID = field.NewInt64(tableName, "user_id")
	_bucketCorsRule.BucketName = field.NewString(tableName, "bucket_name")
	_bucketCorsRule.AllowedOrigin = field.NewString(tableName, "allowed_origin")
	_bucketCorsRule.AllowedMethods = field.NewString(tableName, "allowed_methods")
	_bucketCorsRule.MaxAgeSeconds = field.NewInt32(tableName, "max_age_seconds")
	_bucketCorsRule.Enabled = field.NewInt32(tableName, "enabled")
	_bucketCorsRule.CreatedAt = field.NewTime(tableName, "created_at")
	_bucketCorsRule.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bucketCorsRule.fillFieldMap()

	return _bucketCorsRule
}

type bucketCorsRule struct {
	bucketCorsRuleDo bucketCorsRuleDo

	ALL            field.Asterisk
	ID             field.Int64
	UserID         field.Int64
	BucketName     field.String
	AllowedOrigin  field.String
	AllowedMethods field.String
	MaxAgeSeconds  field.Int32
	Enabled        field.Int32
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (b bucketCorsRule) Table(newTableName string) *bucketCorsRule {
	b.bucketCorsRuleDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bucketCorsRule) As(alias string) *bucketCorsRule {
	b.bucketCorsRuleDo.DO = *(b.bucketCorsRuleDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bucketCorsRule) updateTableName(table string) *bucketCorsRule {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.UserID = field.NewInt64(table, "user_id")
	b.BucketName = field.NewString(table, "bucket_name")
	b.AllowedOrigin = field.NewString(table, "allowed_origin")
	b.AllowedMethods = field.NewString(table, "allowed_methods")
	b.MaxAgeSeconds = field.NewInt32(table, "max_age_seconds")
	b.Enabled = field.NewInt32(table, "enabled")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bucketCorsRule) WithContext(ctx context.Context) *bucketCorsRuleDo {
	return b.bucketCorsRuleDo.WithContext(ctx)
}

func (b bucketCorsRule) TableName() string { return b.bucketCorsRuleDo.TableName() }

func (b bucketCorsRule) Alias() string { return b.bucketCorsRuleDo.Alias() }

func (b bucketCorsRule) Columns(cols ...field.Expr) gen.Columns {
	return b.bucketCorsRuleDo.Columns(cols...)
}

func (b *bucketCorsRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bucketCorsRule) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["bucket_name"] = b.BucketName
	b.fieldMap["allowed_origin"] = b.AllowedOrigin
	b.fieldMap["allowed_methods"] = b.AllowedMethods
	b.fieldMap["max_age_seconds"] = b.MaxAgeSeconds
	b.fieldMap["enabled"] = b.Enabled
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bucketCorsRule) clone(db *gorm.DB) bucketCorsRule {
	b.bucketCorsRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bucketCorsRule) replaceDB(db *gorm.DB) bucketCorsRule {
	b.bucketCorsRuleDo.ReplaceDB(db)
	return b
}

type bucketCorsRuleDo struct{ gen.DO }

func (b bucketCorsRuleDo) Debug() *bucketCorsRuleDo {
	return b.withDO(b.DO.Debug())
}

func (b bucketCorsRuleDo) WithContext(ctx context.Context) *bucketCorsRuleDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bucketCorsRuleDo) ReadDB() *bucketCorsRuleDo {
	return b.Clauses(dbresolver.Read)
}

func (b bucketCorsRuleDo) WriteDB() *bucketCorsRuleDo {
	return b.Clauses(dbresolver.Write)
}

func (b bucketCorsRuleDo) Session(config *gorm.Session) *bucketCorsRuleDo {
	return b.withDO(b.DO.Session(config))
}

func (b bucketCorsRuleDo) Clauses(conds ...clause.Expression) *bucketCorsRuleDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bucketCorsRuleDo) Returning(value interface{}, columns ...string) *bucketCorsRuleDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bucketCorsRuleDo) Not(conds ...gen.Condition) *bucketCorsRuleDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bucketCorsRuleDo) Or(conds ...gen.Condition) *bucketCorsRuleDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bucketCorsRuleDo) Select(conds ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bucketCorsRuleDo) Where(conds ...gen.Condition) *bucketCorsRuleDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bucketCorsRuleDo) Order(conds ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bucketCorsRuleDo) Distinct(cols ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bucketCorsRuleDo) Omit(cols ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bucketCorsRuleDo) Join(table schema.Tabler, on ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bucketCorsRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bucketCorsRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bucketCorsRuleDo) Group(cols ...field.Expr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bucketCorsRuleDo) Having(conds ...gen.Condition) *bucketCorsRuleDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bucketCorsRuleDo) Limit(limit int) *bucketCorsRuleDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bucketCorsRuleDo) Offset(offset int) *bucketCorsRuleDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bucketCorsRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bucketCorsRuleDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bucketCorsRuleDo) Unscoped() *bucketCorsRuleDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bucketCorsRuleDo) Create(values ...*model.BucketCorsRule) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bucketCorsRuleDo) CreateInBatches(values []*model.BucketCorsRule, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bucketCorsRuleDo) Save(values ...*model.BucketCorsRule) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bucketCorsRuleDo) First() (*model.BucketCorsRule, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketCorsRule), nil
	}
}

func (b bucketCorsRuleDo) Take() (*model.BucketCorsRule, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketCorsRule), nil
	}
}

func (b bucketCorsRuleDo) Last() (*model.BucketCorsRule, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketCorsRule), nil
	}
}

func (b bucketCorsRuleDo) Find() ([]*model.BucketCorsRule, error) {
	result, err := b.DO.Find()
	return result.([]*model.BucketCorsRule), err
}

func (b bucketCorsRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BucketCorsRule, err error) {
	buf := make([]*model.BucketCorsRule, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bucketCorsRuleDo) FindInBatches(result *[]*model.BucketCorsRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bucketCorsRuleDo) Attrs(attrs ...field.AssignExpr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bucketCorsRuleDo) Assign(attrs ...field.AssignExpr) *bucketCorsRuleDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bucketCorsRuleDo) Joins(fields ...field.RelationField) *bucketCorsRuleDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bucketCorsRuleDo) Preload(fields ...field.RelationField) *bucketCorsRuleDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bucketCorsRuleDo) FirstOrInit() (*model.BucketCorsRule, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketCorsRule), nil
	}
}

func (b bucketCorsRuleDo) FirstOrCreate() (*model.BucketCorsRule, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketCorsRule), nil
	}
}

func (b bucketCorsRuleDo) FindByPage(offset int, limit int) (result []*model.BucketCorsRule, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bucketCorsRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bucketCorsRuleDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bucketCorsRuleDo) Delete(models ...*model.BucketCorsRule) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bucketCorsRuleDo) withDO(do gen.Dao) *bucketCorsRuleDo {
	b.DO = *do.(*gen.DO)
	return b
}
