// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newBucketPolicy(db *gorm.DB, opts ...gen.DOOption) bucketPolicy {
	_bucketPolicy := bucketPolicy{}

	_bucketPolicy.bucketPolicyDo.UseDB(db, opts...)
	_bucketPolicy.bucketPolicyDo.UseModel(&model.BucketPolicy{})

	tableName := _bucketPolicy.bucketPolicyDo.TableName()
	_bucketPolicy.ALL = field.NewAsterisk(tableName)
	_bucketPolicy.ID = field.NewInt64(tableName, "id")
	_bucketPolicy.BucketID = field.NewInt64(tableName, "bucket_id")
	_bucketPolicy.Effect = field.NewString(tableName, "effect")
	_bucketPolicy.Name = field.NewString(tableName, "name")
	_bucketPolicy.Status = field.NewInt32(tableName, "status")
	_bucketPolicy.CreatedAt = field.NewTime(tableName, "created_at")
	_bucketPolicy.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bucketPolicy.fillFieldMap()

	return _bucketPolicy
}

// bucketPolicy Bucket 权限策略头表
type bucketPolicy struct {
	bucketPolicyDo bucketPolicyDo

	ALL       field.Asterisk
	ID        field.Int64  // 策略ID
	BucketID  field.Int64  // 所属BucketID
	Effect    field.String // Allow / Deny
	Name      field.String // 策略名称
	Status    field.Int32  // 1=启用 0=禁用
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (b bucketPolicy) Table(newTableName string) *bucketPolicy {
	b.bucketPolicyDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bucketPolicy) As(alias string) *bucketPolicy {
	b.bucketPolicyDo.DO = *(b.bucketPolicyDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bucketPolicy) updateTableName(table string) *bucketPolicy {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.BucketID = field.NewInt64(table, "bucket_id")
	b.Effect = field.NewString(table, "effect")
	b.Name = field.NewString(table, "name")
	b.Status = field.NewInt32(table, "status")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bucketPolicy) WithContext(ctx context.Context) *bucketPolicyDo {
	return b.bucketPolicyDo.WithContext(ctx)
}

func (b bucketPolicy) TableName() string { return b.bucketPolicyDo.TableName() }

func (b bucketPolicy) Alias() string { return b.bucketPolicyDo.Alias() }

func (b bucketPolicy) Columns(cols ...field.Expr) gen.Columns {
	return b.bucketPolicyDo.Columns(cols...)
}

func (b *bucketPolicy) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bucketPolicy) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 7)
	b.fieldMap["id"] = b.ID
	b.fieldMap["bucket_id"] = b.BucketID
	b.fieldMap["effect"] = b.Effect
	b.fieldMap["name"] = b.Name
	b.fieldMap["status"] = b.Status
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bucketPolicy) clone(db *gorm.DB) bucketPolicy {
	b.bucketPolicyDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bucketPolicy) replaceDB(db *gorm.DB) bucketPolicy {
	b.bucketPolicyDo.ReplaceDB(db)
	return b
}

type bucketPolicyDo struct{ gen.DO }

func (b bucketPolicyDo) Debug() *bucketPolicyDo {
	return b.withDO(b.DO.Debug())
}

func (b bucketPolicyDo) WithContext(ctx context.Context) *bucketPolicyDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bucketPolicyDo) ReadDB() *bucketPolicyDo {
	return b.Clauses(dbresolver.Read)
}

func (b bucketPolicyDo) WriteDB() *bucketPolicyDo {
	return b.Clauses(dbresolver.Write)
}

func (b bucketPolicyDo) Session(config *gorm.Session) *bucketPolicyDo {
	return b.withDO(b.DO.Session(config))
}

func (b bucketPolicyDo) Clauses(conds ...clause.Expression) *bucketPolicyDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bucketPolicyDo) Returning(value interface{}, columns ...string) *bucketPolicyDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bucketPolicyDo) Not(conds ...gen.Condition) *bucketPolicyDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bucketPolicyDo) Or(conds ...gen.Condition) *bucketPolicyDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bucketPolicyDo) Select(conds ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bucketPolicyDo) Where(conds ...gen.Condition) *bucketPolicyDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bucketPolicyDo) Order(conds ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bucketPolicyDo) Distinct(cols ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bucketPolicyDo) Omit(cols ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bucketPolicyDo) Join(table schema.Tabler, on ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bucketPolicyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bucketPolicyDo) RightJoin(table schema.Tabler, on ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bucketPolicyDo) Group(cols ...field.Expr) *bucketPolicyDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bucketPolicyDo) Having(conds ...gen.Condition) *bucketPolicyDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bucketPolicyDo) Limit(limit int) *bucketPolicyDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bucketPolicyDo) Offset(offset int) *bucketPolicyDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bucketPolicyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bucketPolicyDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bucketPolicyDo) Unscoped() *bucketPolicyDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bucketPolicyDo) Create(values ...*model.BucketPolicy) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bucketPolicyDo) CreateInBatches(values []*model.BucketPolicy, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bucketPolicyDo) Save(values ...*model.BucketPolicy) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bucketPolicyDo) First() (*model.BucketPolicy, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketPolicy), nil
	}
}

func (b bucketPolicyDo) Take() (*model.BucketPolicy, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketPolicy), nil
	}
}

func (b bucketPolicyDo) Last() (*model.BucketPolicy, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketPolicy), nil
	}
}

func (b bucketPolicyDo) Find() ([]*model.BucketPolicy, error) {
	result, err := b.DO.Find()
	return result.([]*model.BucketPolicy), err
}

func (b bucketPolicyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BucketPolicy, err error) {
	buf := make([]*model.BucketPolicy, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bucketPolicyDo) FindInBatches(result *[]*model.BucketPolicy, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bucketPolicyDo) Attrs(attrs ...field.AssignExpr) *bucketPolicyDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bucketPolicyDo) Assign(attrs ...field.AssignExpr) *bucketPolicyDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bucketPolicyDo) Joins(fields ...field.RelationField) *bucketPolicyDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bucketPolicyDo) Preload(fields ...field.RelationField) *bucketPolicyDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bucketPolicyDo) FirstOrInit() (*model.BucketPolicy, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketPolicy), nil
	}
}

func (b bucketPolicyDo) FirstOrCreate() (*model.BucketPolicy, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BucketPolicy), nil
	}
}

func (b bucketPolicyDo) FindByPage(offset int, limit int) (result []*model.BucketPolicy, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bucketPolicyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bucketPolicyDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bucketPolicyDo) Delete(models ...*model.BucketPolicy) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bucketPolicyDo) withDO(do gen.Dao) *bucketPolicyDo {
	b.DO = *do.(*gen.DO)
	return b
}
