// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newBucket(db *gorm.DB, opts ...gen.DOOption) bucket {
	_bucket := bucket{}

	_bucket.bucketDo.UseDB(db, opts...)
	_bucket.bucketDo.UseModel(&model.Bucket{})

	tableName := _bucket.bucketDo.TableName()
	_bucket.ALL = field.NewAsterisk(tableName)
	_bucket.ID = field.NewInt64(tableName, "id")
	_bucket.UserID = field.NewInt64(tableName, "user_id")
	_bucket.Name = field.NewString(tableName, "name")
	_bucket.Region = field.NewString(tableName, "region")
	_bucket.Acl = field.NewInt32(tableName, "acl")
	_bucket.Versioning = field.NewInt32(tableName, "versioning")
	_bucket.Status = field.NewInt32(tableName, "status")
	_bucket.StorageClass = field.NewString(tableName, "storage_class")
	_bucket.ObjectCount = field.NewInt64(tableName, "object_count")
	_bucket.StorageSize = field.NewInt64(tableName, "storage_size")
	_bucket.CreatedAt = field.NewTime(tableName, "created_at")
	_bucket.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bucket.fillFieldMap()

	return _bucket
}

// bucket Bucket 表
type bucket struct {
	bucketDo bucketDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键
	UserID       field.Int64  // 所属用户ID
	Name         field.String // Bucket名(全局唯一)
	Region       field.String // 所在区域
	Acl          field.Int32  // 1=私有 2=公共读 3=公共读写
	Versioning   field.Int32  // 1=关闭 2=开启版本控制
	Status       field.Int32  // 1=正常 2=锁定 3=删除
	StorageClass field.String // STANDARD/IA/ARCHIVE
	ObjectCount  field.Int64  // 对象总数
	StorageSize  field.Int64  // 存储总量(字节)
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (b bucket) Table(newTableName string) *bucket {
	b.bucketDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bucket) As(alias string) *bucket {
	b.bucketDo.DO = *(b.bucketDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bucket) updateTableName(table string) *bucket {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.UserID = field.NewInt64(table, "user_id")
	b.Name = field.NewString(table, "name")
	b.Region = field.NewString(table, "region")
	b.Acl = field.NewInt32(table, "acl")
	b.Versioning = field.NewInt32(table, "versioning")
	b.Status = field.NewInt32(table, "status")
	b.StorageClass = field.NewString(table, "storage_class")
	b.ObjectCount = field.NewInt64(table, "object_count")
	b.StorageSize = field.NewInt64(table, "storage_size")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bucket) WithContext(ctx context.Context) *bucketDo { return b.bucketDo.WithContext(ctx) }

func (b bucket) TableName() string { return b.bucketDo.TableName() }

func (b bucket) Alias() string { return b.bucketDo.Alias() }

func (b bucket) Columns(cols ...field.Expr) gen.Columns { return b.bucketDo.Columns(cols...) }

func (b *bucket) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bucket) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 12)
	b.fieldMap["id"] = b.ID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["name"] = b.Name
	b.fieldMap["region"] = b.Region
	b.fieldMap["acl"] = b.Acl
	b.fieldMap["versioning"] = b.Versioning
	b.fieldMap["status"] = b.Status
	b.fieldMap["storage_class"] = b.StorageClass
	b.fieldMap["object_count"] = b.ObjectCount
	b.fieldMap["storage_size"] = b.StorageSize
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bucket) clone(db *gorm.DB) bucket {
	b.bucketDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bucket) replaceDB(db *gorm.DB) bucket {
	b.bucketDo.ReplaceDB(db)
	return b
}

type bucketDo struct{ gen.DO }

func (b bucketDo) Debug() *bucketDo {
	return b.withDO(b.DO.Debug())
}

func (b bucketDo) WithContext(ctx context.Context) *bucketDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bucketDo) ReadDB() *bucketDo {
	return b.Clauses(dbresolver.Read)
}

func (b bucketDo) WriteDB() *bucketDo {
	return b.Clauses(dbresolver.Write)
}

func (b bucketDo) Session(config *gorm.Session) *bucketDo {
	return b.withDO(b.DO.Session(config))
}

func (b bucketDo) Clauses(conds ...clause.Expression) *bucketDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bucketDo) Returning(value interface{}, columns ...string) *bucketDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bucketDo) Not(conds ...gen.Condition) *bucketDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bucketDo) Or(conds ...gen.Condition) *bucketDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bucketDo) Select(conds ...field.Expr) *bucketDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bucketDo) Where(conds ...gen.Condition) *bucketDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bucketDo) Order(conds ...field.Expr) *bucketDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bucketDo) Distinct(cols ...field.Expr) *bucketDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bucketDo) Omit(cols ...field.Expr) *bucketDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bucketDo) Join(table schema.Tabler, on ...field.Expr) *bucketDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bucketDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bucketDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bucketDo) RightJoin(table schema.Tabler, on ...field.Expr) *bucketDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bucketDo) Group(cols ...field.Expr) *bucketDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bucketDo) Having(conds ...gen.Condition) *bucketDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bucketDo) Limit(limit int) *bucketDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bucketDo) Offset(offset int) *bucketDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bucketDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bucketDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bucketDo) Unscoped() *bucketDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bucketDo) Create(values ...*model.Bucket) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bucketDo) CreateInBatches(values []*model.Bucket, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bucketDo) Save(values ...*model.Bucket) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bucketDo) First() (*model.Bucket, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bucket), nil
	}
}

func (b bucketDo) Take() (*model.Bucket, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bucket), nil
	}
}

func (b bucketDo) Last() (*model.Bucket, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bucket), nil
	}
}

func (b bucketDo) Find() ([]*model.Bucket, error) {
	result, err := b.DO.Find()
	return result.([]*model.Bucket), err
}

func (b bucketDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Bucket, err error) {
	buf := make([]*model.Bucket, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bucketDo) FindInBatches(result *[]*model.Bucket, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bucketDo) Attrs(attrs ...field.AssignExpr) *bucketDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bucketDo) Assign(attrs ...field.AssignExpr) *bucketDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bucketDo) Joins(fields ...field.RelationField) *bucketDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bucketDo) Preload(fields ...field.RelationField) *bucketDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bucketDo) FirstOrInit() (*model.Bucket, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bucket), nil
	}
}

func (b bucketDo) FirstOrCreate() (*model.Bucket, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bucket), nil
	}
}

func (b bucketDo) FindByPage(offset int, limit int) (result []*model.Bucket, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bucketDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bucketDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bucketDo) Delete(models ...*model.Bucket) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bucketDo) withDO(do gen.Dao) *bucketDo {
	b.DO = *do.(*gen.DO)
	return b
}
