// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newEventDelivery(db *gorm.DB, opts ...gen.DOOption) eventDelivery {
	_eventDelivery := eventDelivery{}

	_eventDelivery.eventDeliveryDo.UseDB(db, opts...)
	_eventDelivery.eventDeliveryDo.UseModel(&model.EventDelivery{})

	tableName := _eventDelivery.eventDeliveryDo.TableName()
	_eventDelivery.ALL = field.NewAsterisk(tableName)
	_eventDelivery.ID = field.NewInt64(tableName, "id")
	_eventDelivery.RuleID = field.NewInt64(tableName, "rule_id")
	_eventDelivery.EventType = field.NewString(tableName, "event_type")
	_eventDelivery.ObjectKey = field.NewString(tableName, "object_key")
	_eventDelivery.Payload = field.NewString(tableName, "payload")
	_eventDelivery.Status = field.NewInt32(tableName, "status")
	_eventDelivery.RetryCount = field.NewInt32(tableName, "retry_count")
	_eventDelivery.ResponseCode = field.NewInt32(tableName, "response_code")
	_eventDelivery.ResponseBody = field.NewString(tableName, "response_body")
	_eventDelivery.NextRetryAt = field.NewTime(tableName, "next_retry_at")
	_eventDelivery.CreatedAt = field.NewTime(tableName, "created_at")
	_eventDelivery.UpdatedAt = field.NewTime(tableName, "updated_at")

	_eventDelivery.fillFieldMap()

	return _eventDelivery
}

// eventDelivery 事件投递记录表
type eventDelivery struct {
	eventDeliveryDo eventDeliveryDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键
	RuleID       field.Int64  // 关联规则ID
	EventType    field.String // 事件类型
	ObjectKey    field.String // 触发事件的对象
	Payload      field.String // 投递内容
	Status       field.Int32  // 0=待投递 1=成功 2=失败
	RetryCount   field.Int32  // 已重试次数
	ResponseCode field.Int32  // Webhook响应码
	ResponseBody field.String // Webhook响应体
	NextRetryAt  field.Time   // 下次重试时间
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (e eventDelivery) Table(newTableName string) *eventDelivery {
	e.eventDeliveryDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventDelivery) As(alias string) *eventDelivery {
	e.eventDeliveryDo.DO = *(e.eventDeliveryDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventDelivery) updateTableName(table string) *eventDelivery {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.RuleID = field.NewInt64(table, "rule_id")
	e.EventType = field.NewString(table, "event_type")
	e.ObjectKey = field.NewString(table, "object_key")
	e.Payload = field.NewString(table, "payload")
	e.Status = field.NewInt32(table, "status")
	e.RetryCount = field.NewInt32(table, "retry_count")
	e.ResponseCode = field.NewInt32(table, "response_code")
	e.ResponseBody = field.NewString(table, "response_body")
	e.NextRetryAt = field.NewTime(table, "next_retry_at")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")

	e.fillFieldMap()

	return e
}

func (e *eventDelivery) WithContext(ctx context.Context) *eventDeliveryDo {
	return e.eventDeliveryDo.WithContext(ctx)
}

func (e eventDelivery) TableName() string { return e.eventDeliveryDo.TableName() }

func (e eventDelivery) Alias() string { return e.eventDeliveryDo.Alias() }

func (e eventDelivery) Columns(cols ...field.Expr) gen.Columns {
	return e.eventDeliveryDo.Columns(cols...)
}

func (e *eventDelivery) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventDelivery) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 12)
	e.fieldMap["id"] = e.ID
	e.fieldMap["rule_id"] = e.RuleID
	e.fieldMap["event_type"] = e.EventType
	e.fieldMap["object_key"] = e.ObjectKey
	e.fieldMap["payload"] = e.Payload
	e.fieldMap["status"] = e.Status
	e.fieldMap["retry_count"] = e.RetryCount
	e.fieldMap["response_code"] = e.ResponseCode
	e.fieldMap["response_body"] = e.ResponseBody
	e.fieldMap["next_retry_at"] = e.NextRetryAt
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
}

func (e eventDelivery) clone(db *gorm.DB) eventDelivery {
	e.eventDeliveryDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventDelivery) replaceDB(db *gorm.DB) eventDelivery {
	e.eventDeliveryDo.ReplaceDB(db)
	return e
}

type eventDeliveryDo struct{ gen.DO }

func (e eventDeliveryDo) Debug() *eventDeliveryDo {
	return e.withDO(e.DO.Debug())
}

func (e eventDeliveryDo) WithContext(ctx context.Context) *eventDeliveryDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventDeliveryDo) ReadDB() *eventDeliveryDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventDeliveryDo) WriteDB() *eventDeliveryDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventDeliveryDo) Session(config *gorm.Session) *eventDeliveryDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventDeliveryDo) Clauses(conds ...clause.Expression) *eventDeliveryDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventDeliveryDo) Returning(value interface{}, columns ...string) *eventDeliveryDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventDeliveryDo) Not(conds ...gen.Condition) *eventDeliveryDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventDeliveryDo) Or(conds ...gen.Condition) *eventDeliveryDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventDeliveryDo) Select(conds ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventDeliveryDo) Where(conds ...gen.Condition) *eventDeliveryDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventDeliveryDo) Order(conds ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventDeliveryDo) Distinct(cols ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventDeliveryDo) Omit(cols ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventDeliveryDo) Join(table schema.Tabler, on ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventDeliveryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventDeliveryDo) RightJoin(table schema.Tabler, on ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventDeliveryDo) Group(cols ...field.Expr) *eventDeliveryDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventDeliveryDo) Having(conds ...gen.Condition) *eventDeliveryDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventDeliveryDo) Limit(limit int) *eventDeliveryDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventDeliveryDo) Offset(offset int) *eventDeliveryDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventDeliveryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *eventDeliveryDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventDeliveryDo) Unscoped() *eventDeliveryDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventDeliveryDo) Create(values ...*model.EventDelivery) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventDeliveryDo) CreateInBatches(values []*model.EventDelivery, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventDeliveryDo) Save(values ...*model.EventDelivery) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventDeliveryDo) First() (*model.EventDelivery, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDelivery), nil
	}
}

func (e eventDeliveryDo) Take() (*model.EventDelivery, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDelivery), nil
	}
}

func (e eventDeliveryDo) Last() (*model.EventDelivery, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDelivery), nil
	}
}

func (e eventDeliveryDo) Find() ([]*model.EventDelivery, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventDelivery), err
}

func (e eventDeliveryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventDelivery, err error) {
	buf := make([]*model.EventDelivery, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventDeliveryDo) FindInBatches(result *[]*model.EventDelivery, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventDeliveryDo) Attrs(attrs ...field.AssignExpr) *eventDeliveryDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventDeliveryDo) Assign(attrs ...field.AssignExpr) *eventDeliveryDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventDeliveryDo) Joins(fields ...field.RelationField) *eventDeliveryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventDeliveryDo) Preload(fields ...field.RelationField) *eventDeliveryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventDeliveryDo) FirstOrInit() (*model.EventDelivery, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDelivery), nil
	}
}

func (e eventDeliveryDo) FirstOrCreate() (*model.EventDelivery, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDelivery), nil
	}
}

func (e eventDeliveryDo) FindByPage(offset int, limit int) (result []*model.EventDelivery, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventDeliveryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventDeliveryDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventDeliveryDo) Delete(models ...*model.EventDelivery) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventDeliveryDo) withDO(do gen.Dao) *eventDeliveryDo {
	e.DO = *do.(*gen.DO)
	return e
}
