// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newEventRule(db *gorm.DB, opts ...gen.DOOption) eventRule {
	_eventRule := eventRule{}

	_eventRule.eventRuleDo.UseDB(db, opts...)
	_eventRule.eventRuleDo.UseModel(&model.EventRule{})

	tableName := _eventRule.eventRuleDo.TableName()
	_eventRule.ALL = field.NewAsterisk(tableName)
	_eventRule.ID = field.NewInt64(tableName, "id")
	_eventRule.BucketID = field.NewInt64(tableName, "bucket_id")
	_eventRule.RuleName = field.NewString(tableName, "rule_name")
	_eventRule.Events = field.NewString(tableName, "events")
	_eventRule.Prefix = field.NewString(tableName, "prefix")
	_eventRule.Suffix = field.NewString(tableName, "suffix")
	_eventRule.TargetType = field.NewString(tableName, "target_type")
	_eventRule.TargetURL = field.NewString(tableName, "target_url")
	_eventRule.Secret = field.NewString(tableName, "secret")
	_eventRule.Status = field.NewInt32(tableName, "status")
	_eventRule.CreatedAt = field.NewTime(tableName, "created_at")
	_eventRule.UpdatedAt = field.NewTime(tableName, "updated_at")

	_eventRule.fillFieldMap()

	return _eventRule
}

// eventRule 事件通知规则表
type eventRule struct {
	eventRuleDo eventRuleDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	BucketID   field.Int64  // 所属BucketID
	RuleName   field.String // 规则名
	Events     field.String // 监听的事件类型
	Prefix     field.String // 对象前缀过滤
	Suffix     field.String // 对象后缀过滤
	TargetType field.String // WEBHOOK/MQ/FUNC
	TargetURL  field.String // 回调地址(Webhook)
	Secret     field.String // Webhook签名密钥
	Status     field.Int32  // 1=启用 0=禁用
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (e eventRule) Table(newTableName string) *eventRule {
	e.eventRuleDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventRule) As(alias string) *eventRule {
	e.eventRuleDo.DO = *(e.eventRuleDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventRule) updateTableName(table string) *eventRule {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.BucketID = field.NewInt64(table, "bucket_id")
	e.RuleName = field.NewString(table, "rule_name")
	e.Events = field.NewString(table, "events")
	e.Prefix = field.NewString(table, "prefix")
	e.Suffix = field.NewString(table, "suffix")
	e.TargetType = field.NewString(table, "target_type")
	e.TargetURL = field.NewString(table, "target_url")
	e.Secret = field.NewString(table, "secret")
	e.Status = field.NewInt32(table, "status")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")

	e.fillFieldMap()

	return e
}

func (e *eventRule) WithContext(ctx context.Context) *eventRuleDo {
	return e.eventRuleDo.WithContext(ctx)
}

func (e eventRule) TableName() string { return e.eventRuleDo.TableName() }

func (e eventRule) Alias() string { return e.eventRuleDo.Alias() }

func (e eventRule) Columns(cols ...field.Expr) gen.Columns { return e.eventRuleDo.Columns(cols...) }

func (e *eventRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventRule) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 12)
	e.fieldMap["id"] = e.ID
	e.fieldMap["bucket_id"] = e.BucketID
	e.fieldMap["rule_name"] = e.RuleName
	e.fieldMap["events"] = e.Events
	e.fieldMap["prefix"] = e.Prefix
	e.fieldMap["suffix"] = e.Suffix
	e.fieldMap["target_type"] = e.TargetType
	e.fieldMap["target_url"] = e.TargetURL
	e.fieldMap["secret"] = e.Secret
	e.fieldMap["status"] = e.Status
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
}

func (e eventRule) clone(db *gorm.DB) eventRule {
	e.eventRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventRule) replaceDB(db *gorm.DB) eventRule {
	e.eventRuleDo.ReplaceDB(db)
	return e
}

type eventRuleDo struct{ gen.DO }

func (e eventRuleDo) Debug() *eventRuleDo {
	return e.withDO(e.DO.Debug())
}

func (e eventRuleDo) WithContext(ctx context.Context) *eventRuleDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventRuleDo) ReadDB() *eventRuleDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventRuleDo) WriteDB() *eventRuleDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventRuleDo) Session(config *gorm.Session) *eventRuleDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventRuleDo) Clauses(conds ...clause.Expression) *eventRuleDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventRuleDo) Returning(value interface{}, columns ...string) *eventRuleDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventRuleDo) Not(conds ...gen.Condition) *eventRuleDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventRuleDo) Or(conds ...gen.Condition) *eventRuleDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventRuleDo) Select(conds ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventRuleDo) Where(conds ...gen.Condition) *eventRuleDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventRuleDo) Order(conds ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventRuleDo) Distinct(cols ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventRuleDo) Omit(cols ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventRuleDo) Join(table schema.Tabler, on ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventRuleDo) Group(cols ...field.Expr) *eventRuleDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventRuleDo) Having(conds ...gen.Condition) *eventRuleDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventRuleDo) Limit(limit int) *eventRuleDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventRuleDo) Offset(offset int) *eventRuleDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *eventRuleDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventRuleDo) Unscoped() *eventRuleDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventRuleDo) Create(values ...*model.EventRule) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventRuleDo) CreateInBatches(values []*model.EventRule, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventRuleDo) Save(values ...*model.EventRule) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventRuleDo) First() (*model.EventRule, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRule), nil
	}
}

func (e eventRuleDo) Take() (*model.EventRule, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRule), nil
	}
}

func (e eventRuleDo) Last() (*model.EventRule, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRule), nil
	}
}

func (e eventRuleDo) Find() ([]*model.EventRule, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventRule), err
}

func (e eventRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventRule, err error) {
	buf := make([]*model.EventRule, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventRuleDo) FindInBatches(result *[]*model.EventRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventRuleDo) Attrs(attrs ...field.AssignExpr) *eventRuleDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventRuleDo) Assign(attrs ...field.AssignExpr) *eventRuleDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventRuleDo) Joins(fields ...field.RelationField) *eventRuleDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventRuleDo) Preload(fields ...field.RelationField) *eventRuleDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventRuleDo) FirstOrInit() (*model.EventRule, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRule), nil
	}
}

func (e eventRuleDo) FirstOrCreate() (*model.EventRule, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRule), nil
	}
}

func (e eventRuleDo) FindByPage(offset int, limit int) (result []*model.EventRule, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventRuleDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventRuleDo) Delete(models ...*model.EventRule) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventRuleDo) withDO(do gen.Dao) *eventRuleDo {
	e.DO = *do.(*gen.DO)
	return e
}
