// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newLifecycleRule(db *gorm.DB, opts ...gen.DOOption) lifecycleRule {
	_lifecycleRule := lifecycleRule{}

	_lifecycleRule.lifecycleRuleDo.UseDB(db, opts...)
	_lifecycleRule.lifecycleRuleDo.UseModel(&model.LifecycleRule{})

	tableName := _lifecycleRule.lifecycleRuleDo.TableName()
	_lifecycleRule.ALL = field.NewAsterisk(tableName)
	_lifecycleRule.ID = field.NewInt64(tableName, "id")
	_lifecycleRule.BucketID = field.NewInt64(tableName, "bucket_id")
	_lifecycleRule.RuleName = field.NewString(tableName, "rule_name")
	_lifecycleRule.Status = field.NewInt32(tableName, "status")
	_lifecycleRule.Prefix = field.NewString(tableName, "prefix")
	_lifecycleRule.TransitionDays = field.NewInt32(tableName, "transition_days")
	_lifecycleRule.TransitionStorageClass = field.NewString(tableName, "transition_storage_class")
	_lifecycleRule.ExpirationDays = field.NewInt32(tableName, "expiration_days")
	_lifecycleRule.NoncurrentVersionExpirationDays = field.NewInt32(tableName, "noncurrent_version_expiration_days")
	_lifecycleRule.AbortIncompleteMultipartDays = field.NewInt32(tableName, "abort_incomplete_multipart_days")
	_lifecycleRule.CreatedAt = field.NewTime(tableName, "created_at")
	_lifecycleRule.UpdatedAt = field.NewTime(tableName, "updated_at")

	_lifecycleRule.fillFieldMap()

	return _lifecycleRule
}

// lifecycleRule 生命周期规则表
type lifecycleRule struct {
	lifecycleRuleDo lifecycleRuleDo

	ALL                             field.Asterisk
	ID                              field.Int64  // 主键
	BucketID                        field.Int64  // 所属BucketID
	RuleName                        field.String // 规则名
	Status                          field.Int32  // 1=启用 0=禁用
	Prefix                          field.String // 匹配对象前缀(NULL=全部)
	TransitionDays                  field.Int32  // N天后转换存储类型
	TransitionStorageClass          field.String // 目标存储类型 IA/ARCHIVE
	ExpirationDays                  field.Int32  // N天后删除对象
	NoncurrentVersionExpirationDays field.Int32  // 非当前版本N天后删除
	AbortIncompleteMultipartDays    field.Int32  // 未完成分片上传N天后清理
	CreatedAt                       field.Time
	UpdatedAt                       field.Time

	fieldMap map[string]field.Expr
}

func (l lifecycleRule) Table(newTableName string) *lifecycleRule {
	l.lifecycleRuleDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lifecycleRule) As(alias string) *lifecycleRule {
	l.lifecycleRuleDo.DO = *(l.lifecycleRuleDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lifecycleRule) updateTableName(table string) *lifecycleRule {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.BucketID = field.NewInt64(table, "bucket_id")
	l.RuleName = field.NewString(table, "rule_name")
	l.Status = field.NewInt32(table, "status")
	l.Prefix = field.NewString(table, "prefix")
	l.TransitionDays = field.NewInt32(table, "transition_days")
	l.TransitionStorageClass = field.NewString(table, "transition_storage_class")
	l.ExpirationDays = field.NewInt32(table, "expiration_days")
	l.NoncurrentVersionExpirationDays = field.NewInt32(table, "noncurrent_version_expiration_days")
	l.AbortIncompleteMultipartDays = field.NewInt32(table, "abort_incomplete_multipart_days")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *lifecycleRule) WithContext(ctx context.Context) *lifecycleRuleDo {
	return l.lifecycleRuleDo.WithContext(ctx)
}

func (l lifecycleRule) TableName() string { return l.lifecycleRuleDo.TableName() }

func (l lifecycleRule) Alias() string { return l.lifecycleRuleDo.Alias() }

func (l lifecycleRule) Columns(cols ...field.Expr) gen.Columns {
	return l.lifecycleRuleDo.Columns(cols...)
}

func (l *lifecycleRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lifecycleRule) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.ID
	l.fieldMap["bucket_id"] = l.BucketID
	l.fieldMap["rule_name"] = l.RuleName
	l.fieldMap["status"] = l.Status
	l.fieldMap["prefix"] = l.Prefix
	l.fieldMap["transition_days"] = l.TransitionDays
	l.fieldMap["transition_storage_class"] = l.TransitionStorageClass
	l.fieldMap["expiration_days"] = l.ExpirationDays
	l.fieldMap["noncurrent_version_expiration_days"] = l.NoncurrentVersionExpirationDays
	l.fieldMap["abort_incomplete_multipart_days"] = l.AbortIncompleteMultipartDays
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l lifecycleRule) clone(db *gorm.DB) lifecycleRule {
	l.lifecycleRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lifecycleRule) replaceDB(db *gorm.DB) lifecycleRule {
	l.lifecycleRuleDo.ReplaceDB(db)
	return l
}

type lifecycleRuleDo struct{ gen.DO }

func (l lifecycleRuleDo) Debug() *lifecycleRuleDo {
	return l.withDO(l.DO.Debug())
}

func (l lifecycleRuleDo) WithContext(ctx context.Context) *lifecycleRuleDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lifecycleRuleDo) ReadDB() *lifecycleRuleDo {
	return l.Clauses(dbresolver.Read)
}

func (l lifecycleRuleDo) WriteDB() *lifecycleRuleDo {
	return l.Clauses(dbresolver.Write)
}

func (l lifecycleRuleDo) Session(config *gorm.Session) *lifecycleRuleDo {
	return l.withDO(l.DO.Session(config))
}

func (l lifecycleRuleDo) Clauses(conds ...clause.Expression) *lifecycleRuleDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lifecycleRuleDo) Returning(value interface{}, columns ...string) *lifecycleRuleDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lifecycleRuleDo) Not(conds ...gen.Condition) *lifecycleRuleDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lifecycleRuleDo) Or(conds ...gen.Condition) *lifecycleRuleDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lifecycleRuleDo) Select(conds ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lifecycleRuleDo) Where(conds ...gen.Condition) *lifecycleRuleDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lifecycleRuleDo) Order(conds ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lifecycleRuleDo) Distinct(cols ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lifecycleRuleDo) Omit(cols ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lifecycleRuleDo) Join(table schema.Tabler, on ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lifecycleRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lifecycleRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lifecycleRuleDo) Group(cols ...field.Expr) *lifecycleRuleDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lifecycleRuleDo) Having(conds ...gen.Condition) *lifecycleRuleDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lifecycleRuleDo) Limit(limit int) *lifecycleRuleDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lifecycleRuleDo) Offset(offset int) *lifecycleRuleDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lifecycleRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lifecycleRuleDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lifecycleRuleDo) Unscoped() *lifecycleRuleDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lifecycleRuleDo) Create(values ...*model.LifecycleRule) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lifecycleRuleDo) CreateInBatches(values []*model.LifecycleRule, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lifecycleRuleDo) Save(values ...*model.LifecycleRule) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lifecycleRuleDo) First() (*model.LifecycleRule, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LifecycleRule), nil
	}
}

func (l lifecycleRuleDo) Take() (*model.LifecycleRule, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LifecycleRule), nil
	}
}

func (l lifecycleRuleDo) Last() (*model.LifecycleRule, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LifecycleRule), nil
	}
}

func (l lifecycleRuleDo) Find() ([]*model.LifecycleRule, error) {
	result, err := l.DO.Find()
	return result.([]*model.LifecycleRule), err
}

func (l lifecycleRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LifecycleRule, err error) {
	buf := make([]*model.LifecycleRule, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lifecycleRuleDo) FindInBatches(result *[]*model.LifecycleRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lifecycleRuleDo) Attrs(attrs ...field.AssignExpr) *lifecycleRuleDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lifecycleRuleDo) Assign(attrs ...field.AssignExpr) *lifecycleRuleDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lifecycleRuleDo) Joins(fields ...field.RelationField) *lifecycleRuleDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lifecycleRuleDo) Preload(fields ...field.RelationField) *lifecycleRuleDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lifecycleRuleDo) FirstOrInit() (*model.LifecycleRule, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LifecycleRule), nil
	}
}

func (l lifecycleRuleDo) FirstOrCreate() (*model.LifecycleRule, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LifecycleRule), nil
	}
}

func (l lifecycleRuleDo) FindByPage(offset int, limit int) (result []*model.LifecycleRule, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lifecycleRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lifecycleRuleDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lifecycleRuleDo) Delete(models ...*model.LifecycleRule) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lifecycleRuleDo) withDO(do gen.Dao) *lifecycleRuleDo {
	l.DO = *do.(*gen.DO)
	return l
}
