// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newMeteringDaily(db *gorm.DB, opts ...gen.DOOption) meteringDaily {
	_meteringDaily := meteringDaily{}

	_meteringDaily.meteringDailyDo.UseDB(db, opts...)
	_meteringDaily.meteringDailyDo.UseModel(&model.MeteringDaily{})

	tableName := _meteringDaily.meteringDailyDo.TableName()
	_meteringDaily.ALL = field.NewAsterisk(tableName)
	_meteringDaily.ID = field.NewInt64(tableName, "id")
	_meteringDaily.UserID = field.NewInt64(tableName, "user_id")
	_meteringDaily.BucketID = field.NewInt64(tableName, "bucket_id")
	_meteringDaily.StatDate = field.NewTime(tableName, "stat_date")
	_meteringDaily.StorageSize = field.NewInt64(tableName, "storage_size")
	_meteringDaily.ObjectCount = field.NewInt64(tableName, "object_count")
	_meteringDaily.UploadFlow = field.NewInt64(tableName, "upload_flow")
	_meteringDaily.DownloadFlow = field.NewInt64(tableName, "download_flow")
	_meteringDaily.GetRequestCount = field.NewInt64(tableName, "get_request_count")
	_meteringDaily.PutRequestCount = field.NewInt64(tableName, "put_request_count")
	_meteringDaily.DelRequestCount = field.NewInt64(tableName, "del_request_count")

	_meteringDaily.fillFieldMap()

	return _meteringDaily
}

// meteringDaily 流量计量日统计表
type meteringDaily struct {
	meteringDailyDo meteringDailyDo

	ALL             field.Asterisk
	ID              field.Int64 // 主键
	UserID          field.Int64 // 用户ID
	BucketID        field.Int64 // BucketID(NULL=用户总计)
	StatDate        field.Time  // 统计日期
	StorageSize     field.Int64 // 存储量(字节)
	ObjectCount     field.Int64 // 对象数量
	UploadFlow      field.Int64 // 上行流量(字节)
	DownloadFlow    field.Int64 // 下行流量(字节)
	GetRequestCount field.Int64 // GET请求次数
	PutRequestCount field.Int64 // PUT请求次数
	DelRequestCount field.Int64 // DELETE请求次数

	fieldMap map[string]field.Expr
}

func (m meteringDaily) Table(newTableName string) *meteringDaily {
	m.meteringDailyDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meteringDaily) As(alias string) *meteringDaily {
	m.meteringDailyDo.DO = *(m.meteringDailyDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meteringDaily) updateTableName(table string) *meteringDaily {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UserID = field.NewInt64(table, "user_id")
	m.BucketID = field.NewInt64(table, "bucket_id")
	m.StatDate = field.NewTime(table, "stat_date")
	m.StorageSize = field.NewInt64(table, "storage_size")
	m.ObjectCount = field.NewInt64(table, "object_count")
	m.UploadFlow = field.NewInt64(table, "upload_flow")
	m.DownloadFlow = field.NewInt64(table, "download_flow")
	m.GetRequestCount = field.NewInt64(table, "get_request_count")
	m.PutRequestCount = field.NewInt64(table, "put_request_count")
	m.DelRequestCount = field.NewInt64(table, "del_request_count")

	m.fillFieldMap()

	return m
}

func (m *meteringDaily) WithContext(ctx context.Context) *meteringDailyDo {
	return m.meteringDailyDo.WithContext(ctx)
}

func (m meteringDaily) TableName() string { return m.meteringDailyDo.TableName() }

func (m meteringDaily) Alias() string { return m.meteringDailyDo.Alias() }

func (m meteringDaily) Columns(cols ...field.Expr) gen.Columns {
	return m.meteringDailyDo.Columns(cols...)
}

func (m *meteringDaily) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meteringDaily) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["bucket_id"] = m.BucketID
	m.fieldMap["stat_date"] = m.StatDate
	m.fieldMap["storage_size"] = m.StorageSize
	m.fieldMap["object_count"] = m.ObjectCount
	m.fieldMap["upload_flow"] = m.UploadFlow
	m.fieldMap["download_flow"] = m.DownloadFlow
	m.fieldMap["get_request_count"] = m.GetRequestCount
	m.fieldMap["put_request_count"] = m.PutRequestCount
	m.fieldMap["del_request_count"] = m.DelRequestCount
}

func (m meteringDaily) clone(db *gorm.DB) meteringDaily {
	m.meteringDailyDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meteringDaily) replaceDB(db *gorm.DB) meteringDaily {
	m.meteringDailyDo.ReplaceDB(db)
	return m
}

type meteringDailyDo struct{ gen.DO }

func (m meteringDailyDo) Debug() *meteringDailyDo {
	return m.withDO(m.DO.Debug())
}

func (m meteringDailyDo) WithContext(ctx context.Context) *meteringDailyDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meteringDailyDo) ReadDB() *meteringDailyDo {
	return m.Clauses(dbresolver.Read)
}

func (m meteringDailyDo) WriteDB() *meteringDailyDo {
	return m.Clauses(dbresolver.Write)
}

func (m meteringDailyDo) Session(config *gorm.Session) *meteringDailyDo {
	return m.withDO(m.DO.Session(config))
}

func (m meteringDailyDo) Clauses(conds ...clause.Expression) *meteringDailyDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meteringDailyDo) Returning(value interface{}, columns ...string) *meteringDailyDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meteringDailyDo) Not(conds ...gen.Condition) *meteringDailyDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meteringDailyDo) Or(conds ...gen.Condition) *meteringDailyDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meteringDailyDo) Select(conds ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meteringDailyDo) Where(conds ...gen.Condition) *meteringDailyDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meteringDailyDo) Order(conds ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meteringDailyDo) Distinct(cols ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meteringDailyDo) Omit(cols ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meteringDailyDo) Join(table schema.Tabler, on ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meteringDailyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meteringDailyDo) RightJoin(table schema.Tabler, on ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meteringDailyDo) Group(cols ...field.Expr) *meteringDailyDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meteringDailyDo) Having(conds ...gen.Condition) *meteringDailyDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meteringDailyDo) Limit(limit int) *meteringDailyDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meteringDailyDo) Offset(offset int) *meteringDailyDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meteringDailyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *meteringDailyDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meteringDailyDo) Unscoped() *meteringDailyDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meteringDailyDo) Create(values ...*model.MeteringDaily) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meteringDailyDo) CreateInBatches(values []*model.MeteringDaily, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meteringDailyDo) Save(values ...*model.MeteringDaily) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meteringDailyDo) First() (*model.MeteringDaily, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeteringDaily), nil
	}
}

func (m meteringDailyDo) Take() (*model.MeteringDaily, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeteringDaily), nil
	}
}

func (m meteringDailyDo) Last() (*model.MeteringDaily, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeteringDaily), nil
	}
}

func (m meteringDailyDo) Find() ([]*model.MeteringDaily, error) {
	result, err := m.DO.Find()
	return result.([]*model.MeteringDaily), err
}

func (m meteringDailyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MeteringDaily, err error) {
	buf := make([]*model.MeteringDaily, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meteringDailyDo) FindInBatches(result *[]*model.MeteringDaily, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meteringDailyDo) Attrs(attrs ...field.AssignExpr) *meteringDailyDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meteringDailyDo) Assign(attrs ...field.AssignExpr) *meteringDailyDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meteringDailyDo) Joins(fields ...field.RelationField) *meteringDailyDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meteringDailyDo) Preload(fields ...field.RelationField) *meteringDailyDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meteringDailyDo) FirstOrInit() (*model.MeteringDaily, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeteringDaily), nil
	}
}

func (m meteringDailyDo) FirstOrCreate() (*model.MeteringDaily, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeteringDaily), nil
	}
}

func (m meteringDailyDo) FindByPage(offset int, limit int) (result []*model.MeteringDaily, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meteringDailyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meteringDailyDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meteringDailyDo) Delete(models ...*model.MeteringDaily) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meteringDailyDo) withDO(do gen.Dao) *meteringDailyDo {
	m.DO = *do.(*gen.DO)
	return m
}
