// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newMultipartUpload(db *gorm.DB, opts ...gen.DOOption) multipartUpload {
	_multipartUpload := multipartUpload{}

	_multipartUpload.multipartUploadDo.UseDB(db, opts...)
	_multipartUpload.multipartUploadDo.UseModel(&model.MultipartUpload{})

	tableName := _multipartUpload.multipartUploadDo.TableName()
	_multipartUpload.ALL = field.NewAsterisk(tableName)
	_multipartUpload.ID = field.NewInt64(tableName, "id")
	_multipartUpload.UploadID = field.NewString(tableName, "upload_id")
	_multipartUpload.BucketID = field.NewInt64(tableName, "bucket_id")
	_multipartUpload.BucketName = field.NewString(tableName, "bucket_name")
	_multipartUpload.ObjectKey = field.NewString(tableName, "object_key")
	_multipartUpload.ObjectKeyHash = field.NewString(tableName, "object_key_hash")
	_multipartUpload.UserID = field.NewInt64(tableName, "user_id")
	_multipartUpload.TotalChunk = field.NewInt32(tableName, "total_chunk")
	_multipartUpload.Status = field.NewInt32(tableName, "status")
	_multipartUpload.StorageClass = field.NewString(tableName, "storage_class")
	_multipartUpload.ContentType = field.NewString(tableName, "content_type")
	_multipartUpload.Metadata = field.NewString(tableName, "metadata")
	_multipartUpload.ExpiresAt = field.NewTime(tableName, "expires_at")
	_multipartUpload.LastActiveAt = field.NewTime(tableName, "last_active_at")
	_multipartUpload.CreatedAt = field.NewTime(tableName, "created_at")
	_multipartUpload.UpdatedAt = field.NewTime(tableName, "updated_at")

	_multipartUpload.fillFieldMap()

	return _multipartUpload
}

// multipartUpload 分片上传会话表
type multipartUpload struct {
	multipartUploadDo multipartUploadDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键
	UploadID      field.String // 上传会话ID(对外暴露)
	BucketID      field.Int64  // 所属BucketID
	BucketName    field.String // Bucket名(冗余)
	ObjectKey     field.String // 目标对象路径
	ObjectKeyHash field.String // MD5(object_key) 用于索引
	UserID        field.Int64  // 发起用户ID
	TotalChunk    field.Int32  // 总分片数
	Status        field.Int32  // 0=上传中 1=合并完成(虚拟) 2=物理合并完成 3=失败 4=已取消
	StorageClass  field.String // 存储类型
	ContentType   field.String // MIME类型
	Metadata      field.String // 用户自定义元数据
	ExpiresAt     field.Time   // 会话过期时间(默认24h)
	LastActiveAt  field.Time   // 最后活跃时间(用于ZSET score)
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m multipartUpload) Table(newTableName string) *multipartUpload {
	m.multipartUploadDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m multipartUpload) As(alias string) *multipartUpload {
	m.multipartUploadDo.DO = *(m.multipartUploadDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *multipartUpload) updateTableName(table string) *multipartUpload {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UploadID = field.NewString(table, "upload_id")
	m.BucketID = field.NewInt64(table, "bucket_id")
	m.BucketName = field.NewString(table, "bucket_name")
	m.ObjectKey = field.NewString(table, "object_key")
	m.ObjectKeyHash = field.NewString(table, "object_key_hash")
	m.UserID = field.NewInt64(table, "user_id")
	m.TotalChunk = field.NewInt32(table, "total_chunk")
	m.Status = field.NewInt32(table, "status")
	m.StorageClass = field.NewString(table, "storage_class")
	m.ContentType = field.NewString(table, "content_type")
	m.Metadata = field.NewString(table, "metadata")
	m.ExpiresAt = field.NewTime(table, "expires_at")
	m.LastActiveAt = field.NewTime(table, "last_active_at")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *multipartUpload) WithContext(ctx context.Context) *multipartUploadDo {
	return m.multipartUploadDo.WithContext(ctx)
}

func (m multipartUpload) TableName() string { return m.multipartUploadDo.TableName() }

func (m multipartUpload) Alias() string { return m.multipartUploadDo.Alias() }

func (m multipartUpload) Columns(cols ...field.Expr) gen.Columns {
	return m.multipartUploadDo.Columns(cols...)
}

func (m *multipartUpload) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *multipartUpload) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 16)
	m.fieldMap["id"] = m.ID
	m.fieldMap["upload_id"] = m.UploadID
	m.fieldMap["bucket_id"] = m.BucketID
	m.fieldMap["bucket_name"] = m.BucketName
	m.fieldMap["object_key"] = m.ObjectKey
	m.fieldMap["object_key_hash"] = m.ObjectKeyHash
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["total_chunk"] = m.TotalChunk
	m.fieldMap["status"] = m.Status
	m.fieldMap["storage_class"] = m.StorageClass
	m.fieldMap["content_type"] = m.ContentType
	m.fieldMap["metadata"] = m.Metadata
	m.fieldMap["expires_at"] = m.ExpiresAt
	m.fieldMap["last_active_at"] = m.LastActiveAt
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m multipartUpload) clone(db *gorm.DB) multipartUpload {
	m.multipartUploadDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m multipartUpload) replaceDB(db *gorm.DB) multipartUpload {
	m.multipartUploadDo.ReplaceDB(db)
	return m
}

type multipartUploadDo struct{ gen.DO }

func (m multipartUploadDo) Debug() *multipartUploadDo {
	return m.withDO(m.DO.Debug())
}

func (m multipartUploadDo) WithContext(ctx context.Context) *multipartUploadDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m multipartUploadDo) ReadDB() *multipartUploadDo {
	return m.Clauses(dbresolver.Read)
}

func (m multipartUploadDo) WriteDB() *multipartUploadDo {
	return m.Clauses(dbresolver.Write)
}

func (m multipartUploadDo) Session(config *gorm.Session) *multipartUploadDo {
	return m.withDO(m.DO.Session(config))
}

func (m multipartUploadDo) Clauses(conds ...clause.Expression) *multipartUploadDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m multipartUploadDo) Returning(value interface{}, columns ...string) *multipartUploadDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m multipartUploadDo) Not(conds ...gen.Condition) *multipartUploadDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m multipartUploadDo) Or(conds ...gen.Condition) *multipartUploadDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m multipartUploadDo) Select(conds ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m multipartUploadDo) Where(conds ...gen.Condition) *multipartUploadDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m multipartUploadDo) Order(conds ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m multipartUploadDo) Distinct(cols ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m multipartUploadDo) Omit(cols ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m multipartUploadDo) Join(table schema.Tabler, on ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m multipartUploadDo) LeftJoin(table schema.Tabler, on ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m multipartUploadDo) RightJoin(table schema.Tabler, on ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m multipartUploadDo) Group(cols ...field.Expr) *multipartUploadDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m multipartUploadDo) Having(conds ...gen.Condition) *multipartUploadDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m multipartUploadDo) Limit(limit int) *multipartUploadDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m multipartUploadDo) Offset(offset int) *multipartUploadDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m multipartUploadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *multipartUploadDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m multipartUploadDo) Unscoped() *multipartUploadDo {
	return m.withDO(m.DO.Unscoped())
}

func (m multipartUploadDo) Create(values ...*model.MultipartUpload) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m multipartUploadDo) CreateInBatches(values []*model.MultipartUpload, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m multipartUploadDo) Save(values ...*model.MultipartUpload) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m multipartUploadDo) First() (*model.MultipartUpload, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartUpload), nil
	}
}

func (m multipartUploadDo) Take() (*model.MultipartUpload, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartUpload), nil
	}
}

func (m multipartUploadDo) Last() (*model.MultipartUpload, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartUpload), nil
	}
}

func (m multipartUploadDo) Find() ([]*model.MultipartUpload, error) {
	result, err := m.DO.Find()
	return result.([]*model.MultipartUpload), err
}

func (m multipartUploadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MultipartUpload, err error) {
	buf := make([]*model.MultipartUpload, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m multipartUploadDo) FindInBatches(result *[]*model.MultipartUpload, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m multipartUploadDo) Attrs(attrs ...field.AssignExpr) *multipartUploadDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m multipartUploadDo) Assign(attrs ...field.AssignExpr) *multipartUploadDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m multipartUploadDo) Joins(fields ...field.RelationField) *multipartUploadDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m multipartUploadDo) Preload(fields ...field.RelationField) *multipartUploadDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m multipartUploadDo) FirstOrInit() (*model.MultipartUpload, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartUpload), nil
	}
}

func (m multipartUploadDo) FirstOrCreate() (*model.MultipartUpload, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartUpload), nil
	}
}

func (m multipartUploadDo) FindByPage(offset int, limit int) (result []*model.MultipartUpload, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m multipartUploadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m multipartUploadDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m multipartUploadDo) Delete(models ...*model.MultipartUpload) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *multipartUploadDo) withDO(do gen.Dao) *multipartUploadDo {
	m.DO = *do.(*gen.DO)
	return m
}
