// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newMultipartPart(db *gorm.DB, opts ...gen.DOOption) multipartPart {
	_multipartPart := multipartPart{}

	_multipartPart.multipartPartDo.UseDB(db, opts...)
	_multipartPart.multipartPartDo.UseModel(&model.MultipartPart{})

	tableName := _multipartPart.multipartPartDo.TableName()
	_multipartPart.ALL = field.NewAsterisk(tableName)
	_multipartPart.ID = field.NewInt64(tableName, "id")
	_multipartPart.UploadID = field.NewString(tableName, "upload_id")
	_multipartPart.PartNumber = field.NewInt32(tableName, "part_number")
	_multipartPart.Size = field.NewInt64(tableName, "size")
	_multipartPart.Etag = field.NewString(tableName, "etag")
	_multipartPart.StoragePath = field.NewString(tableName, "storage_path")
	_multipartPart.Status = field.NewInt32(tableName, "status")
	_multipartPart.CreatedAt = field.NewTime(tableName, "created_at")

	_multipartPart.fillFieldMap()

	return _multipartPart
}

// multipartPart 分片明细表
type multipartPart struct {
	multipartPartDo multipartPartDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键
	UploadID    field.String // 所属上传会话ID
	PartNumber  field.Int32  // 分片序号 1~10000
	Size        field.Int64  // 分片大小(字节)
	Etag        field.String // 分片MD5
	StoragePath field.String // 分片物理存储路径
	Status      field.Int32  // 0=上传中 1=已确认(虚拟合并) 2=物理合并完可删
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m multipartPart) Table(newTableName string) *multipartPart {
	m.multipartPartDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m multipartPart) As(alias string) *multipartPart {
	m.multipartPartDo.DO = *(m.multipartPartDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *multipartPart) updateTableName(table string) *multipartPart {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UploadID = field.NewString(table, "upload_id")
	m.PartNumber = field.NewInt32(table, "part_number")
	m.Size = field.NewInt64(table, "size")
	m.Etag = field.NewString(table, "etag")
	m.StoragePath = field.NewString(table, "storage_path")
	m.Status = field.NewInt32(table, "status")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *multipartPart) WithContext(ctx context.Context) *multipartPartDo {
	return m.multipartPartDo.WithContext(ctx)
}

func (m multipartPart) TableName() string { return m.multipartPartDo.TableName() }

func (m multipartPart) Alias() string { return m.multipartPartDo.Alias() }

func (m multipartPart) Columns(cols ...field.Expr) gen.Columns {
	return m.multipartPartDo.Columns(cols...)
}

func (m *multipartPart) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *multipartPart) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["id"] = m.ID
	m.fieldMap["upload_id"] = m.UploadID
	m.fieldMap["part_number"] = m.PartNumber
	m.fieldMap["size"] = m.Size
	m.fieldMap["etag"] = m.Etag
	m.fieldMap["storage_path"] = m.StoragePath
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m multipartPart) clone(db *gorm.DB) multipartPart {
	m.multipartPartDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m multipartPart) replaceDB(db *gorm.DB) multipartPart {
	m.multipartPartDo.ReplaceDB(db)
	return m
}

type multipartPartDo struct{ gen.DO }

func (m multipartPartDo) Debug() *multipartPartDo {
	return m.withDO(m.DO.Debug())
}

func (m multipartPartDo) WithContext(ctx context.Context) *multipartPartDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m multipartPartDo) ReadDB() *multipartPartDo {
	return m.Clauses(dbresolver.Read)
}

func (m multipartPartDo) WriteDB() *multipartPartDo {
	return m.Clauses(dbresolver.Write)
}

func (m multipartPartDo) Session(config *gorm.Session) *multipartPartDo {
	return m.withDO(m.DO.Session(config))
}

func (m multipartPartDo) Clauses(conds ...clause.Expression) *multipartPartDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m multipartPartDo) Returning(value interface{}, columns ...string) *multipartPartDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m multipartPartDo) Not(conds ...gen.Condition) *multipartPartDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m multipartPartDo) Or(conds ...gen.Condition) *multipartPartDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m multipartPartDo) Select(conds ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m multipartPartDo) Where(conds ...gen.Condition) *multipartPartDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m multipartPartDo) Order(conds ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m multipartPartDo) Distinct(cols ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m multipartPartDo) Omit(cols ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m multipartPartDo) Join(table schema.Tabler, on ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m multipartPartDo) LeftJoin(table schema.Tabler, on ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m multipartPartDo) RightJoin(table schema.Tabler, on ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m multipartPartDo) Group(cols ...field.Expr) *multipartPartDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m multipartPartDo) Having(conds ...gen.Condition) *multipartPartDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m multipartPartDo) Limit(limit int) *multipartPartDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m multipartPartDo) Offset(offset int) *multipartPartDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m multipartPartDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *multipartPartDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m multipartPartDo) Unscoped() *multipartPartDo {
	return m.withDO(m.DO.Unscoped())
}

func (m multipartPartDo) Create(values ...*model.MultipartPart) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m multipartPartDo) CreateInBatches(values []*model.MultipartPart, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m multipartPartDo) Save(values ...*model.MultipartPart) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m multipartPartDo) First() (*model.MultipartPart, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartPart), nil
	}
}

func (m multipartPartDo) Take() (*model.MultipartPart, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartPart), nil
	}
}

func (m multipartPartDo) Last() (*model.MultipartPart, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartPart), nil
	}
}

func (m multipartPartDo) Find() ([]*model.MultipartPart, error) {
	result, err := m.DO.Find()
	return result.([]*model.MultipartPart), err
}

func (m multipartPartDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MultipartPart, err error) {
	buf := make([]*model.MultipartPart, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m multipartPartDo) FindInBatches(result *[]*model.MultipartPart, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m multipartPartDo) Attrs(attrs ...field.AssignExpr) *multipartPartDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m multipartPartDo) Assign(attrs ...field.AssignExpr) *multipartPartDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m multipartPartDo) Joins(fields ...field.RelationField) *multipartPartDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m multipartPartDo) Preload(fields ...field.RelationField) *multipartPartDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m multipartPartDo) FirstOrInit() (*model.MultipartPart, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartPart), nil
	}
}

func (m multipartPartDo) FirstOrCreate() (*model.MultipartPart, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultipartPart), nil
	}
}

func (m multipartPartDo) FindByPage(offset int, limit int) (result []*model.MultipartPart, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m multipartPartDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m multipartPartDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m multipartPartDo) Delete(models ...*model.MultipartPart) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *multipartPartDo) withDO(do gen.Dao) *multipartPartDo {
	m.DO = *do.(*gen.DO)
	return m
}
