// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newObject(db *gorm.DB, opts ...gen.DOOption) object {
	_object := object{}

	_object.objectDo.UseDB(db, opts...)
	_object.objectDo.UseModel(&model.Object{})

	tableName := _object.objectDo.TableName()
	_object.ALL = field.NewAsterisk(tableName)
	_object.ID = field.NewInt64(tableName, "id")
	_object.BucketID = field.NewInt64(tableName, "bucket_id")
	_object.BucketName = field.NewString(tableName, "bucket_name")
	_object.ObjectKey = field.NewString(tableName, "object_key")
	_object.ObjectKeyHash = field.NewString(tableName, "object_key_hash")
	_object.VersionID = field.NewString(tableName, "version_id")
	_object.Size = field.NewInt64(tableName, "size")
	_object.Etag = field.NewString(tableName, "etag")
	_object.ContentType = field.NewString(tableName, "content_type")
	_object.StorageClass = field.NewString(tableName, "storage_class")
	_object.IsMultipart = field.NewInt32(tableName, "is_multipart")
	_object.UploadID = field.NewString(tableName, "upload_id")
	_object.StoragePath = field.NewString(tableName, "storage_path")
	_object.Acl = field.NewInt32(tableName, "acl")
	_object.IsLatest = field.NewInt32(tableName, "is_latest")
	_object.Metadata = field.NewString(tableName, "metadata")
	_object.Status = field.NewInt32(tableName, "status")
	_object.AccessCount = field.NewInt64(tableName, "access_count")
	_object.CreatedAt = field.NewTime(tableName, "created_at")
	_object.UpdatedAt = field.NewTime(tableName, "updated_at")
	_object.DeletedAt = field.NewField(tableName, "deleted_at")

	_object.fillFieldMap()

	return _object
}

// object Object 对象表
type object struct {
	objectDo objectDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键
	BucketID      field.Int64  // 所属BucketID
	BucketName    field.String // Bucket名(冗余)
	ObjectKey     field.String // 对象路径 e.g. dir/video.mp4
	ObjectKeyHash field.String // MD5(object_key) 用于唯一索引
	VersionID     field.String // 版本ID(未开启版本控制时为空字符串)
	Size          field.Int64  // 文件大小(字节)
	Etag          field.String // MD5 或分片合并ETag
	ContentType   field.String // MIME类型
	StorageClass  field.String
	IsMultipart   field.Int32  // 0=普通上传 1=分片虚拟合并
	UploadID      field.String // 分片上传ID(is_multipart=1时)
	StoragePath   field.String // 物理路径(普通文件或物理合并后)
	Acl           field.Int32  // 0=继承Bucket 1=私有 2=公共读
	IsLatest      field.Int32
	Metadata      field.String // 用户自定义元数据
	Status        field.Int32  // 1=正常 2=删除标记(版本控制) 3=物理删除
	AccessCount   field.Int64  // 访问次数(懒合并触发依据)
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field // 软删除时间

	fieldMap map[string]field.Expr
}

func (o object) Table(newTableName string) *object {
	o.objectDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o object) As(alias string) *object {
	o.objectDo.DO = *(o.objectDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *object) updateTableName(table string) *object {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.BucketID = field.NewInt64(table, "bucket_id")
	o.BucketName = field.NewString(table, "bucket_name")
	o.ObjectKey = field.NewString(table, "object_key")
	o.ObjectKeyHash = field.NewString(table, "object_key_hash")
	o.VersionID = field.NewString(table, "version_id")
	o.Size = field.NewInt64(table, "size")
	o.Etag = field.NewString(table, "etag")
	o.ContentType = field.NewString(table, "content_type")
	o.StorageClass = field.NewString(table, "storage_class")
	o.IsMultipart = field.NewInt32(table, "is_multipart")
	o.UploadID = field.NewString(table, "upload_id")
	o.StoragePath = field.NewString(table, "storage_path")
	o.Acl = field.NewInt32(table, "acl")
	o.IsLatest = field.NewInt32(table, "is_latest")
	o.Metadata = field.NewString(table, "metadata")
	o.Status = field.NewInt32(table, "status")
	o.AccessCount = field.NewInt64(table, "access_count")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")

	o.fillFieldMap()

	return o
}

func (o *object) WithContext(ctx context.Context) *objectDo { return o.objectDo.WithContext(ctx) }

func (o object) TableName() string { return o.objectDo.TableName() }

func (o object) Alias() string { return o.objectDo.Alias() }

func (o object) Columns(cols ...field.Expr) gen.Columns { return o.objectDo.Columns(cols...) }

func (o *object) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *object) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 21)
	o.fieldMap["id"] = o.ID
	o.fieldMap["bucket_id"] = o.BucketID
	o.fieldMap["bucket_name"] = o.BucketName
	o.fieldMap["object_key"] = o.ObjectKey
	o.fieldMap["object_key_hash"] = o.ObjectKeyHash
	o.fieldMap["version_id"] = o.VersionID
	o.fieldMap["size"] = o.Size
	o.fieldMap["etag"] = o.Etag
	o.fieldMap["content_type"] = o.ContentType
	o.fieldMap["storage_class"] = o.StorageClass
	o.fieldMap["is_multipart"] = o.IsMultipart
	o.fieldMap["upload_id"] = o.UploadID
	o.fieldMap["storage_path"] = o.StoragePath
	o.fieldMap["acl"] = o.Acl
	o.fieldMap["is_latest"] = o.IsLatest
	o.fieldMap["metadata"] = o.Metadata
	o.fieldMap["status"] = o.Status
	o.fieldMap["access_count"] = o.AccessCount
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
}

func (o object) clone(db *gorm.DB) object {
	o.objectDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o object) replaceDB(db *gorm.DB) object {
	o.objectDo.ReplaceDB(db)
	return o
}

type objectDo struct{ gen.DO }

func (o objectDo) Debug() *objectDo {
	return o.withDO(o.DO.Debug())
}

func (o objectDo) WithContext(ctx context.Context) *objectDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o objectDo) ReadDB() *objectDo {
	return o.Clauses(dbresolver.Read)
}

func (o objectDo) WriteDB() *objectDo {
	return o.Clauses(dbresolver.Write)
}

func (o objectDo) Session(config *gorm.Session) *objectDo {
	return o.withDO(o.DO.Session(config))
}

func (o objectDo) Clauses(conds ...clause.Expression) *objectDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o objectDo) Returning(value interface{}, columns ...string) *objectDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o objectDo) Not(conds ...gen.Condition) *objectDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o objectDo) Or(conds ...gen.Condition) *objectDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o objectDo) Select(conds ...field.Expr) *objectDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o objectDo) Where(conds ...gen.Condition) *objectDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o objectDo) Order(conds ...field.Expr) *objectDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o objectDo) Distinct(cols ...field.Expr) *objectDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o objectDo) Omit(cols ...field.Expr) *objectDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o objectDo) Join(table schema.Tabler, on ...field.Expr) *objectDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o objectDo) LeftJoin(table schema.Tabler, on ...field.Expr) *objectDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o objectDo) RightJoin(table schema.Tabler, on ...field.Expr) *objectDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o objectDo) Group(cols ...field.Expr) *objectDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o objectDo) Having(conds ...gen.Condition) *objectDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o objectDo) Limit(limit int) *objectDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o objectDo) Offset(offset int) *objectDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o objectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *objectDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o objectDo) Unscoped() *objectDo {
	return o.withDO(o.DO.Unscoped())
}

func (o objectDo) Create(values ...*model.Object) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o objectDo) CreateInBatches(values []*model.Object, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o objectDo) Save(values ...*model.Object) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o objectDo) First() (*model.Object, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Object), nil
	}
}

func (o objectDo) Take() (*model.Object, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Object), nil
	}
}

func (o objectDo) Last() (*model.Object, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Object), nil
	}
}

func (o objectDo) Find() ([]*model.Object, error) {
	result, err := o.DO.Find()
	return result.([]*model.Object), err
}

func (o objectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Object, err error) {
	buf := make([]*model.Object, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o objectDo) FindInBatches(result *[]*model.Object, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o objectDo) Attrs(attrs ...field.AssignExpr) *objectDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o objectDo) Assign(attrs ...field.AssignExpr) *objectDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o objectDo) Joins(fields ...field.RelationField) *objectDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o objectDo) Preload(fields ...field.RelationField) *objectDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o objectDo) FirstOrInit() (*model.Object, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Object), nil
	}
}

func (o objectDo) FirstOrCreate() (*model.Object, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Object), nil
	}
}

func (o objectDo) FindByPage(offset int, limit int) (result []*model.Object, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o objectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o objectDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o objectDo) Delete(models ...*model.Object) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *objectDo) withDO(do gen.Dao) *objectDo {
	o.DO = *do.(*gen.DO)
	return o
}
