// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newPolicyPrincipal(db *gorm.DB, opts ...gen.DOOption) policyPrincipal {
	_policyPrincipal := policyPrincipal{}

	_policyPrincipal.policyPrincipalDo.UseDB(db, opts...)
	_policyPrincipal.policyPrincipalDo.UseModel(&model.PolicyPrincipal{})

	tableName := _policyPrincipal.policyPrincipalDo.TableName()
	_policyPrincipal.ALL = field.NewAsterisk(tableName)
	_policyPrincipal.ID = field.NewInt64(tableName, "id")
	_policyPrincipal.PolicyID = field.NewInt64(tableName, "policy_id")
	_policyPrincipal.Type = field.NewString(tableName, "type")
	_policyPrincipal.Value = field.NewString(tableName, "value")

	_policyPrincipal.fillFieldMap()

	return _policyPrincipal
}

// policyPrincipal 策略授权主体表
type policyPrincipal struct {
	policyPrincipalDo policyPrincipalDo

	ALL      field.Asterisk
	ID       field.Int64  // 主键
	PolicyID field.Int64  // 策略ID
	Type     field.String // 主体类型(user/ak/role)
	Value    field.String // 主体值(如 user_id 或 ak)

	fieldMap map[string]field.Expr
}

func (p policyPrincipal) Table(newTableName string) *policyPrincipal {
	p.policyPrincipalDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyPrincipal) As(alias string) *policyPrincipal {
	p.policyPrincipalDo.DO = *(p.policyPrincipalDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyPrincipal) updateTableName(table string) *policyPrincipal {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PolicyID = field.NewInt64(table, "policy_id")
	p.Type = field.NewString(table, "type")
	p.Value = field.NewString(table, "value")

	p.fillFieldMap()

	return p
}

func (p *policyPrincipal) WithContext(ctx context.Context) *policyPrincipalDo {
	return p.policyPrincipalDo.WithContext(ctx)
}

func (p policyPrincipal) TableName() string { return p.policyPrincipalDo.TableName() }

func (p policyPrincipal) Alias() string { return p.policyPrincipalDo.Alias() }

func (p policyPrincipal) Columns(cols ...field.Expr) gen.Columns {
	return p.policyPrincipalDo.Columns(cols...)
}

func (p *policyPrincipal) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyPrincipal) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["policy_id"] = p.PolicyID
	p.fieldMap["type"] = p.Type
	p.fieldMap["value"] = p.Value
}

func (p policyPrincipal) clone(db *gorm.DB) policyPrincipal {
	p.policyPrincipalDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyPrincipal) replaceDB(db *gorm.DB) policyPrincipal {
	p.policyPrincipalDo.ReplaceDB(db)
	return p
}

type policyPrincipalDo struct{ gen.DO }

func (p policyPrincipalDo) Debug() *policyPrincipalDo {
	return p.withDO(p.DO.Debug())
}

func (p policyPrincipalDo) WithContext(ctx context.Context) *policyPrincipalDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyPrincipalDo) ReadDB() *policyPrincipalDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyPrincipalDo) WriteDB() *policyPrincipalDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyPrincipalDo) Session(config *gorm.Session) *policyPrincipalDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyPrincipalDo) Clauses(conds ...clause.Expression) *policyPrincipalDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyPrincipalDo) Returning(value interface{}, columns ...string) *policyPrincipalDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyPrincipalDo) Not(conds ...gen.Condition) *policyPrincipalDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyPrincipalDo) Or(conds ...gen.Condition) *policyPrincipalDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyPrincipalDo) Select(conds ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyPrincipalDo) Where(conds ...gen.Condition) *policyPrincipalDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyPrincipalDo) Order(conds ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyPrincipalDo) Distinct(cols ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyPrincipalDo) Omit(cols ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyPrincipalDo) Join(table schema.Tabler, on ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyPrincipalDo) LeftJoin(table schema.Tabler, on ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyPrincipalDo) RightJoin(table schema.Tabler, on ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyPrincipalDo) Group(cols ...field.Expr) *policyPrincipalDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyPrincipalDo) Having(conds ...gen.Condition) *policyPrincipalDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyPrincipalDo) Limit(limit int) *policyPrincipalDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyPrincipalDo) Offset(offset int) *policyPrincipalDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyPrincipalDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *policyPrincipalDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyPrincipalDo) Unscoped() *policyPrincipalDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyPrincipalDo) Create(values ...*model.PolicyPrincipal) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyPrincipalDo) CreateInBatches(values []*model.PolicyPrincipal, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyPrincipalDo) Save(values ...*model.PolicyPrincipal) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyPrincipalDo) First() (*model.PolicyPrincipal, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyPrincipal), nil
	}
}

func (p policyPrincipalDo) Take() (*model.PolicyPrincipal, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyPrincipal), nil
	}
}

func (p policyPrincipalDo) Last() (*model.PolicyPrincipal, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyPrincipal), nil
	}
}

func (p policyPrincipalDo) Find() ([]*model.PolicyPrincipal, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyPrincipal), err
}

func (p policyPrincipalDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyPrincipal, err error) {
	buf := make([]*model.PolicyPrincipal, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyPrincipalDo) FindInBatches(result *[]*model.PolicyPrincipal, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyPrincipalDo) Attrs(attrs ...field.AssignExpr) *policyPrincipalDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyPrincipalDo) Assign(attrs ...field.AssignExpr) *policyPrincipalDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyPrincipalDo) Joins(fields ...field.RelationField) *policyPrincipalDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyPrincipalDo) Preload(fields ...field.RelationField) *policyPrincipalDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyPrincipalDo) FirstOrInit() (*model.PolicyPrincipal, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyPrincipal), nil
	}
}

func (p policyPrincipalDo) FirstOrCreate() (*model.PolicyPrincipal, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyPrincipal), nil
	}
}

func (p policyPrincipalDo) FindByPage(offset int, limit int) (result []*model.PolicyPrincipal, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyPrincipalDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyPrincipalDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyPrincipalDo) Delete(models ...*model.PolicyPrincipal) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyPrincipalDo) withDO(do gen.Dao) *policyPrincipalDo {
	p.DO = *do.(*gen.DO)
	return p
}
