// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newPolicyAction(db *gorm.DB, opts ...gen.DOOption) policyAction {
	_policyAction := policyAction{}

	_policyAction.policyActionDo.UseDB(db, opts...)
	_policyAction.policyActionDo.UseModel(&model.PolicyAction{})

	tableName := _policyAction.policyActionDo.TableName()
	_policyAction.ALL = field.NewAsterisk(tableName)
	_policyAction.ID = field.NewInt64(tableName, "id")
	_policyAction.PolicyID = field.NewInt64(tableName, "policy_id")
	_policyAction.Action = field.NewString(tableName, "action")

	_policyAction.fillFieldMap()

	return _policyAction
}

// policyAction 策略操作表
type policyAction struct {
	policyActionDo policyActionDo

	ALL      field.Asterisk
	ID       field.Int64  // 主键
	PolicyID field.Int64  // 策略ID
	Action   field.String // 操作名(如 GetObject)

	fieldMap map[string]field.Expr
}

func (p policyAction) Table(newTableName string) *policyAction {
	p.policyActionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyAction) As(alias string) *policyAction {
	p.policyActionDo.DO = *(p.policyActionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyAction) updateTableName(table string) *policyAction {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PolicyID = field.NewInt64(table, "policy_id")
	p.Action = field.NewString(table, "action")

	p.fillFieldMap()

	return p
}

func (p *policyAction) WithContext(ctx context.Context) *policyActionDo {
	return p.policyActionDo.WithContext(ctx)
}

func (p policyAction) TableName() string { return p.policyActionDo.TableName() }

func (p policyAction) Alias() string { return p.policyActionDo.Alias() }

func (p policyAction) Columns(cols ...field.Expr) gen.Columns {
	return p.policyActionDo.Columns(cols...)
}

func (p *policyAction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyAction) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["policy_id"] = p.PolicyID
	p.fieldMap["action"] = p.Action
}

func (p policyAction) clone(db *gorm.DB) policyAction {
	p.policyActionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyAction) replaceDB(db *gorm.DB) policyAction {
	p.policyActionDo.ReplaceDB(db)
	return p
}

type policyActionDo struct{ gen.DO }

func (p policyActionDo) Debug() *policyActionDo {
	return p.withDO(p.DO.Debug())
}

func (p policyActionDo) WithContext(ctx context.Context) *policyActionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyActionDo) ReadDB() *policyActionDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyActionDo) WriteDB() *policyActionDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyActionDo) Session(config *gorm.Session) *policyActionDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyActionDo) Clauses(conds ...clause.Expression) *policyActionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyActionDo) Returning(value interface{}, columns ...string) *policyActionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyActionDo) Not(conds ...gen.Condition) *policyActionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyActionDo) Or(conds ...gen.Condition) *policyActionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyActionDo) Select(conds ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyActionDo) Where(conds ...gen.Condition) *policyActionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyActionDo) Order(conds ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyActionDo) Distinct(cols ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyActionDo) Omit(cols ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyActionDo) Join(table schema.Tabler, on ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyActionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyActionDo) RightJoin(table schema.Tabler, on ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyActionDo) Group(cols ...field.Expr) *policyActionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyActionDo) Having(conds ...gen.Condition) *policyActionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyActionDo) Limit(limit int) *policyActionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyActionDo) Offset(offset int) *policyActionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyActionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *policyActionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyActionDo) Unscoped() *policyActionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyActionDo) Create(values ...*model.PolicyAction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyActionDo) CreateInBatches(values []*model.PolicyAction, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyActionDo) Save(values ...*model.PolicyAction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyActionDo) First() (*model.PolicyAction, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyAction), nil
	}
}

func (p policyActionDo) Take() (*model.PolicyAction, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyAction), nil
	}
}

func (p policyActionDo) Last() (*model.PolicyAction, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyAction), nil
	}
}

func (p policyActionDo) Find() ([]*model.PolicyAction, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyAction), err
}

func (p policyActionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyAction, err error) {
	buf := make([]*model.PolicyAction, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyActionDo) FindInBatches(result *[]*model.PolicyAction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyActionDo) Attrs(attrs ...field.AssignExpr) *policyActionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyActionDo) Assign(attrs ...field.AssignExpr) *policyActionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyActionDo) Joins(fields ...field.RelationField) *policyActionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyActionDo) Preload(fields ...field.RelationField) *policyActionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyActionDo) FirstOrInit() (*model.PolicyAction, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyAction), nil
	}
}

func (p policyActionDo) FirstOrCreate() (*model.PolicyAction, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyAction), nil
	}
}

func (p policyActionDo) FindByPage(offset int, limit int) (result []*model.PolicyAction, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyActionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyActionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyActionDo) Delete(models ...*model.PolicyAction) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyActionDo) withDO(do gen.Dao) *policyActionDo {
	p.DO = *do.(*gen.DO)
	return p
}
