// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newPolicyCondition(db *gorm.DB, opts ...gen.DOOption) policyCondition {
	_policyCondition := policyCondition{}

	_policyCondition.policyConditionDo.UseDB(db, opts...)
	_policyCondition.policyConditionDo.UseModel(&model.PolicyCondition{})

	tableName := _policyCondition.policyConditionDo.TableName()
	_policyCondition.ALL = field.NewAsterisk(tableName)
	_policyCondition.ID = field.NewInt64(tableName, "id")
	_policyCondition.PolicyID = field.NewInt64(tableName, "policy_id")
	_policyCondition.Type = field.NewString(tableName, "type")
	_policyCondition.CondKey = field.NewString(tableName, "cond_key")
	_policyCondition.Value = field.NewString(tableName, "value")

	_policyCondition.fillFieldMap()

	return _policyCondition
}

// policyCondition 策略条件表
type policyCondition struct {
	policyConditionDo policyConditionDo

	ALL      field.Asterisk
	ID       field.Int64  // 主键
	PolicyID field.Int64  // 策略ID
	Type     field.String // 条件类型(ip/time/etc)
	CondKey  field.String // 条件键(start/end/...)
	Value    field.String // 条件值

	fieldMap map[string]field.Expr
}

func (p policyCondition) Table(newTableName string) *policyCondition {
	p.policyConditionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyCondition) As(alias string) *policyCondition {
	p.policyConditionDo.DO = *(p.policyConditionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyCondition) updateTableName(table string) *policyCondition {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PolicyID = field.NewInt64(table, "policy_id")
	p.Type = field.NewString(table, "type")
	p.CondKey = field.NewString(table, "cond_key")
	p.Value = field.NewString(table, "value")

	p.fillFieldMap()

	return p
}

func (p *policyCondition) WithContext(ctx context.Context) *policyConditionDo {
	return p.policyConditionDo.WithContext(ctx)
}

func (p policyCondition) TableName() string { return p.policyConditionDo.TableName() }

func (p policyCondition) Alias() string { return p.policyConditionDo.Alias() }

func (p policyCondition) Columns(cols ...field.Expr) gen.Columns {
	return p.policyConditionDo.Columns(cols...)
}

func (p *policyCondition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyCondition) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["policy_id"] = p.PolicyID
	p.fieldMap["type"] = p.Type
	p.fieldMap["cond_key"] = p.CondKey
	p.fieldMap["value"] = p.Value
}

func (p policyCondition) clone(db *gorm.DB) policyCondition {
	p.policyConditionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyCondition) replaceDB(db *gorm.DB) policyCondition {
	p.policyConditionDo.ReplaceDB(db)
	return p
}

type policyConditionDo struct{ gen.DO }

func (p policyConditionDo) Debug() *policyConditionDo {
	return p.withDO(p.DO.Debug())
}

func (p policyConditionDo) WithContext(ctx context.Context) *policyConditionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyConditionDo) ReadDB() *policyConditionDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyConditionDo) WriteDB() *policyConditionDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyConditionDo) Session(config *gorm.Session) *policyConditionDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyConditionDo) Clauses(conds ...clause.Expression) *policyConditionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyConditionDo) Returning(value interface{}, columns ...string) *policyConditionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyConditionDo) Not(conds ...gen.Condition) *policyConditionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyConditionDo) Or(conds ...gen.Condition) *policyConditionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyConditionDo) Select(conds ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyConditionDo) Where(conds ...gen.Condition) *policyConditionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyConditionDo) Order(conds ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyConditionDo) Distinct(cols ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyConditionDo) Omit(cols ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyConditionDo) Join(table schema.Tabler, on ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyConditionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyConditionDo) RightJoin(table schema.Tabler, on ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyConditionDo) Group(cols ...field.Expr) *policyConditionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyConditionDo) Having(conds ...gen.Condition) *policyConditionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyConditionDo) Limit(limit int) *policyConditionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyConditionDo) Offset(offset int) *policyConditionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyConditionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *policyConditionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyConditionDo) Unscoped() *policyConditionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyConditionDo) Create(values ...*model.PolicyCondition) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyConditionDo) CreateInBatches(values []*model.PolicyCondition, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyConditionDo) Save(values ...*model.PolicyCondition) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyConditionDo) First() (*model.PolicyCondition, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyCondition), nil
	}
}

func (p policyConditionDo) Take() (*model.PolicyCondition, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyCondition), nil
	}
}

func (p policyConditionDo) Last() (*model.PolicyCondition, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyCondition), nil
	}
}

func (p policyConditionDo) Find() ([]*model.PolicyCondition, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyCondition), err
}

func (p policyConditionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyCondition, err error) {
	buf := make([]*model.PolicyCondition, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyConditionDo) FindInBatches(result *[]*model.PolicyCondition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyConditionDo) Attrs(attrs ...field.AssignExpr) *policyConditionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyConditionDo) Assign(attrs ...field.AssignExpr) *policyConditionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyConditionDo) Joins(fields ...field.RelationField) *policyConditionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyConditionDo) Preload(fields ...field.RelationField) *policyConditionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyConditionDo) FirstOrInit() (*model.PolicyCondition, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyCondition), nil
	}
}

func (p policyConditionDo) FirstOrCreate() (*model.PolicyCondition, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyCondition), nil
	}
}

func (p policyConditionDo) FindByPage(offset int, limit int) (result []*model.PolicyCondition, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyConditionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyConditionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyConditionDo) Delete(models ...*model.PolicyCondition) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyConditionDo) withDO(do gen.Dao) *policyConditionDo {
	p.DO = *do.(*gen.DO)
	return p
}
