// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newPolicyResource(db *gorm.DB, opts ...gen.DOOption) policyResource {
	_policyResource := policyResource{}

	_policyResource.policyResourceDo.UseDB(db, opts...)
	_policyResource.policyResourceDo.UseModel(&model.PolicyResource{})

	tableName := _policyResource.policyResourceDo.TableName()
	_policyResource.ALL = field.NewAsterisk(tableName)
	_policyResource.ID = field.NewInt64(tableName, "id")
	_policyResource.PolicyID = field.NewInt64(tableName, "policy_id")
	_policyResource.Resource = field.NewString(tableName, "resource")

	_policyResource.fillFieldMap()

	return _policyResource
}

// policyResource 策略资源表
type policyResource struct {
	policyResourceDo policyResourceDo

	ALL      field.Asterisk
	ID       field.Int64  // 主键
	PolicyID field.Int64  // 策略ID
	Resource field.String // 资源路径(如 bucketName/*)

	fieldMap map[string]field.Expr
}

func (p policyResource) Table(newTableName string) *policyResource {
	p.policyResourceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policyResource) As(alias string) *policyResource {
	p.policyResourceDo.DO = *(p.policyResourceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policyResource) updateTableName(table string) *policyResource {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PolicyID = field.NewInt64(table, "policy_id")
	p.Resource = field.NewString(table, "resource")

	p.fillFieldMap()

	return p
}

func (p *policyResource) WithContext(ctx context.Context) *policyResourceDo {
	return p.policyResourceDo.WithContext(ctx)
}

func (p policyResource) TableName() string { return p.policyResourceDo.TableName() }

func (p policyResource) Alias() string { return p.policyResourceDo.Alias() }

func (p policyResource) Columns(cols ...field.Expr) gen.Columns {
	return p.policyResourceDo.Columns(cols...)
}

func (p *policyResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policyResource) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["policy_id"] = p.PolicyID
	p.fieldMap["resource"] = p.Resource
}

func (p policyResource) clone(db *gorm.DB) policyResource {
	p.policyResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policyResource) replaceDB(db *gorm.DB) policyResource {
	p.policyResourceDo.ReplaceDB(db)
	return p
}

type policyResourceDo struct{ gen.DO }

func (p policyResourceDo) Debug() *policyResourceDo {
	return p.withDO(p.DO.Debug())
}

func (p policyResourceDo) WithContext(ctx context.Context) *policyResourceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policyResourceDo) ReadDB() *policyResourceDo {
	return p.Clauses(dbresolver.Read)
}

func (p policyResourceDo) WriteDB() *policyResourceDo {
	return p.Clauses(dbresolver.Write)
}

func (p policyResourceDo) Session(config *gorm.Session) *policyResourceDo {
	return p.withDO(p.DO.Session(config))
}

func (p policyResourceDo) Clauses(conds ...clause.Expression) *policyResourceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policyResourceDo) Returning(value interface{}, columns ...string) *policyResourceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policyResourceDo) Not(conds ...gen.Condition) *policyResourceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policyResourceDo) Or(conds ...gen.Condition) *policyResourceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policyResourceDo) Select(conds ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policyResourceDo) Where(conds ...gen.Condition) *policyResourceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policyResourceDo) Order(conds ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policyResourceDo) Distinct(cols ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policyResourceDo) Omit(cols ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policyResourceDo) Join(table schema.Tabler, on ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policyResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policyResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policyResourceDo) Group(cols ...field.Expr) *policyResourceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policyResourceDo) Having(conds ...gen.Condition) *policyResourceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policyResourceDo) Limit(limit int) *policyResourceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policyResourceDo) Offset(offset int) *policyResourceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policyResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *policyResourceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policyResourceDo) Unscoped() *policyResourceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policyResourceDo) Create(values ...*model.PolicyResource) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policyResourceDo) CreateInBatches(values []*model.PolicyResource, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policyResourceDo) Save(values ...*model.PolicyResource) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policyResourceDo) First() (*model.PolicyResource, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyResource), nil
	}
}

func (p policyResourceDo) Take() (*model.PolicyResource, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyResource), nil
	}
}

func (p policyResourceDo) Last() (*model.PolicyResource, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyResource), nil
	}
}

func (p policyResourceDo) Find() ([]*model.PolicyResource, error) {
	result, err := p.DO.Find()
	return result.([]*model.PolicyResource), err
}

func (p policyResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PolicyResource, err error) {
	buf := make([]*model.PolicyResource, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policyResourceDo) FindInBatches(result *[]*model.PolicyResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policyResourceDo) Attrs(attrs ...field.AssignExpr) *policyResourceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policyResourceDo) Assign(attrs ...field.AssignExpr) *policyResourceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policyResourceDo) Joins(fields ...field.RelationField) *policyResourceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policyResourceDo) Preload(fields ...field.RelationField) *policyResourceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policyResourceDo) FirstOrInit() (*model.PolicyResource, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyResource), nil
	}
}

func (p policyResourceDo) FirstOrCreate() (*model.PolicyResource, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PolicyResource), nil
	}
}

func (p policyResourceDo) FindByPage(offset int, limit int) (result []*model.PolicyResource, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policyResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policyResourceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policyResourceDo) Delete(models ...*model.PolicyResource) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policyResourceDo) withDO(do gen.Dao) *policyResourceDo {
	p.DO = *do.(*gen.DO)
	return p
}
