// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newPresignedURL(db *gorm.DB, opts ...gen.DOOption) presignedURL {
	_presignedURL := presignedURL{}

	_presignedURL.presignedURLDo.UseDB(db, opts...)
	_presignedURL.presignedURLDo.UseModel(&model.PresignedURL{})

	tableName := _presignedURL.presignedURLDo.TableName()
	_presignedURL.ALL = field.NewAsterisk(tableName)
	_presignedURL.ID = field.NewInt64(tableName, "id")
	_presignedURL.Token = field.NewString(tableName, "token")
	_presignedURL.BucketID = field.NewInt64(tableName, "bucket_id")
	_presignedURL.ObjectKey = field.NewString(tableName, "object_key")
	_presignedURL.ObjectKeyHash = field.NewString(tableName, "object_key_hash")
	_presignedURL.Method = field.NewString(tableName, "method")
	_presignedURL.UserID = field.NewInt64(tableName, "user_id")
	_presignedURL.SingleUse = field.NewInt32(tableName, "single_use")
	_presignedURL.Used = field.NewInt32(tableName, "used")
	_presignedURL.ExpiresAt = field.NewTime(tableName, "expires_at")
	_presignedURL.CreatedAt = field.NewTime(tableName, "created_at")

	_presignedURL.fillFieldMap()

	return _presignedURL
}

// presignedURL 预签名URL表
type presignedURL struct {
	presignedURLDo presignedURLDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键
	Token         field.String // 签名Token
	BucketID      field.Int64  // 所属BucketID
	ObjectKey     field.String // 目标对象路径
	ObjectKeyHash field.String // MD5(object_key) 用于索引
	Method        field.String // GET(下载)/PUT(上传)
	UserID        field.Int64  // 签发用户
	SingleUse     field.Int32  // 0=多次 1=单次使用
	Used          field.Int32  // 是否已使用
	ExpiresAt     field.Time   // 过期时间
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (p presignedURL) Table(newTableName string) *presignedURL {
	p.presignedURLDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p presignedURL) As(alias string) *presignedURL {
	p.presignedURLDo.DO = *(p.presignedURLDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *presignedURL) updateTableName(table string) *presignedURL {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Token = field.NewString(table, "token")
	p.BucketID = field.NewInt64(table, "bucket_id")
	p.ObjectKey = field.NewString(table, "object_key")
	p.ObjectKeyHash = field.NewString(table, "object_key_hash")
	p.Method = field.NewString(table, "method")
	p.UserID = field.NewInt64(table, "user_id")
	p.SingleUse = field.NewInt32(table, "single_use")
	p.Used = field.NewInt32(table, "used")
	p.ExpiresAt = field.NewTime(table, "expires_at")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *presignedURL) WithContext(ctx context.Context) *presignedURLDo {
	return p.presignedURLDo.WithContext(ctx)
}

func (p presignedURL) TableName() string { return p.presignedURLDo.TableName() }

func (p presignedURL) Alias() string { return p.presignedURLDo.Alias() }

func (p presignedURL) Columns(cols ...field.Expr) gen.Columns {
	return p.presignedURLDo.Columns(cols...)
}

func (p *presignedURL) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *presignedURL) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["token"] = p.Token
	p.fieldMap["bucket_id"] = p.BucketID
	p.fieldMap["object_key"] = p.ObjectKey
	p.fieldMap["object_key_hash"] = p.ObjectKeyHash
	p.fieldMap["method"] = p.Method
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["single_use"] = p.SingleUse
	p.fieldMap["used"] = p.Used
	p.fieldMap["expires_at"] = p.ExpiresAt
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p presignedURL) clone(db *gorm.DB) presignedURL {
	p.presignedURLDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p presignedURL) replaceDB(db *gorm.DB) presignedURL {
	p.presignedURLDo.ReplaceDB(db)
	return p
}

type presignedURLDo struct{ gen.DO }

func (p presignedURLDo) Debug() *presignedURLDo {
	return p.withDO(p.DO.Debug())
}

func (p presignedURLDo) WithContext(ctx context.Context) *presignedURLDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p presignedURLDo) ReadDB() *presignedURLDo {
	return p.Clauses(dbresolver.Read)
}

func (p presignedURLDo) WriteDB() *presignedURLDo {
	return p.Clauses(dbresolver.Write)
}

func (p presignedURLDo) Session(config *gorm.Session) *presignedURLDo {
	return p.withDO(p.DO.Session(config))
}

func (p presignedURLDo) Clauses(conds ...clause.Expression) *presignedURLDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p presignedURLDo) Returning(value interface{}, columns ...string) *presignedURLDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p presignedURLDo) Not(conds ...gen.Condition) *presignedURLDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p presignedURLDo) Or(conds ...gen.Condition) *presignedURLDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p presignedURLDo) Select(conds ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p presignedURLDo) Where(conds ...gen.Condition) *presignedURLDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p presignedURLDo) Order(conds ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p presignedURLDo) Distinct(cols ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p presignedURLDo) Omit(cols ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p presignedURLDo) Join(table schema.Tabler, on ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p presignedURLDo) LeftJoin(table schema.Tabler, on ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p presignedURLDo) RightJoin(table schema.Tabler, on ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p presignedURLDo) Group(cols ...field.Expr) *presignedURLDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p presignedURLDo) Having(conds ...gen.Condition) *presignedURLDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p presignedURLDo) Limit(limit int) *presignedURLDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p presignedURLDo) Offset(offset int) *presignedURLDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p presignedURLDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *presignedURLDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p presignedURLDo) Unscoped() *presignedURLDo {
	return p.withDO(p.DO.Unscoped())
}

func (p presignedURLDo) Create(values ...*model.PresignedURL) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p presignedURLDo) CreateInBatches(values []*model.PresignedURL, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p presignedURLDo) Save(values ...*model.PresignedURL) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p presignedURLDo) First() (*model.PresignedURL, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PresignedURL), nil
	}
}

func (p presignedURLDo) Take() (*model.PresignedURL, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PresignedURL), nil
	}
}

func (p presignedURLDo) Last() (*model.PresignedURL, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PresignedURL), nil
	}
}

func (p presignedURLDo) Find() ([]*model.PresignedURL, error) {
	result, err := p.DO.Find()
	return result.([]*model.PresignedURL), err
}

func (p presignedURLDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PresignedURL, err error) {
	buf := make([]*model.PresignedURL, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p presignedURLDo) FindInBatches(result *[]*model.PresignedURL, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p presignedURLDo) Attrs(attrs ...field.AssignExpr) *presignedURLDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p presignedURLDo) Assign(attrs ...field.AssignExpr) *presignedURLDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p presignedURLDo) Joins(fields ...field.RelationField) *presignedURLDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p presignedURLDo) Preload(fields ...field.RelationField) *presignedURLDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p presignedURLDo) FirstOrInit() (*model.PresignedURL, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PresignedURL), nil
	}
}

func (p presignedURLDo) FirstOrCreate() (*model.PresignedURL, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PresignedURL), nil
	}
}

func (p presignedURLDo) FindByPage(offset int, limit int) (result []*model.PresignedURL, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p presignedURLDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p presignedURLDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p presignedURLDo) Delete(models ...*model.PresignedURL) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *presignedURLDo) withDO(do gen.Dao) *presignedURLDo {
	p.DO = *do.(*gen.DO)
	return p
}
