// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newVideoTranscode(db *gorm.DB, opts ...gen.DOOption) videoTranscode {
	_videoTranscode := videoTranscode{}

	_videoTranscode.videoTranscodeDo.UseDB(db, opts...)
	_videoTranscode.videoTranscodeDo.UseModel(&model.VideoTranscode{})

	tableName := _videoTranscode.videoTranscodeDo.TableName()
	_videoTranscode.ALL = field.NewAsterisk(tableName)
	_videoTranscode.ID = field.NewInt64(tableName, "id")
	_videoTranscode.UserID = field.NewInt64(tableName, "user_id")
	_videoTranscode.BucketID = field.NewInt64(tableName, "bucket_id")
	_videoTranscode.BucketName = field.NewString(tableName, "bucket_name")
	_videoTranscode.ObjectID = field.NewInt64(tableName, "object_id")
	_videoTranscode.ObjectKey = field.NewString(tableName, "object_key")
	_videoTranscode.ObjectKeyHash = field.NewString(tableName, "object_key_hash")
	_videoTranscode.VersionID = field.NewString(tableName, "version_id")
	_videoTranscode.SourceEtag = field.NewString(tableName, "source_etag")
	_videoTranscode.SourceSize = field.NewInt64(tableName, "source_size")
	_videoTranscode.Status = field.NewInt32(tableName, "status")
	_videoTranscode.DurationMs = field.NewInt64(tableName, "duration_ms")
	_videoTranscode.DerivedSize = field.NewInt64(tableName, "derived_size")
	_videoTranscode.ProfileCount = field.NewInt32(tableName, "profile_count")
	_videoTranscode.DoneProfileCount = field.NewInt32(tableName, "done_profile_count")
	_videoTranscode.LastError = field.NewString(tableName, "last_error")
	_videoTranscode.CreatedAt = field.NewTime(tableName, "created_at")
	_videoTranscode.UpdatedAt = field.NewTime(tableName, "updated_at")
	_videoTranscode.FinishedAt = field.NewTime(tableName, "finished_at")

	_videoTranscode.fillFieldMap()

	return _videoTranscode
}

type videoTranscode struct {
	videoTranscodeDo videoTranscodeDo

	ALL              field.Asterisk
	ID               field.Int64
	UserID           field.Int64
	BucketID         field.Int64
	BucketName       field.String
	ObjectID         field.Int64
	ObjectKey        field.String
	ObjectKeyHash    field.String
	VersionID        field.String
	SourceEtag       field.String
	SourceSize       field.Int64
	Status           field.Int32 // 0=pending 1=processing 2=done 3=failed 4=deleted
	DurationMs       field.Int64
	DerivedSize      field.Int64
	ProfileCount     field.Int32
	DoneProfileCount field.Int32
	LastError        field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	FinishedAt       field.Time

	fieldMap map[string]field.Expr
}

func (v videoTranscode) Table(newTableName string) *videoTranscode {
	v.videoTranscodeDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoTranscode) As(alias string) *videoTranscode {
	v.videoTranscodeDo.DO = *(v.videoTranscodeDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoTranscode) updateTableName(table string) *videoTranscode {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.UserID = field.NewInt64(table, "user_id")
	v.BucketID = field.NewInt64(table, "bucket_id")
	v.BucketName = field.NewString(table, "bucket_name")
	v.ObjectID = field.NewInt64(table, "object_id")
	v.ObjectKey = field.NewString(table, "object_key")
	v.ObjectKeyHash = field.NewString(table, "object_key_hash")
	v.VersionID = field.NewString(table, "version_id")
	v.SourceEtag = field.NewString(table, "source_etag")
	v.SourceSize = field.NewInt64(table, "source_size")
	v.Status = field.NewInt32(table, "status")
	v.DurationMs = field.NewInt64(table, "duration_ms")
	v.DerivedSize = field.NewInt64(table, "derived_size")
	v.ProfileCount = field.NewInt32(table, "profile_count")
	v.DoneProfileCount = field.NewInt32(table, "done_profile_count")
	v.LastError = field.NewString(table, "last_error")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")
	v.FinishedAt = field.NewTime(table, "finished_at")

	v.fillFieldMap()

	return v
}

func (v *videoTranscode) WithContext(ctx context.Context) *videoTranscodeDo {
	return v.videoTranscodeDo.WithContext(ctx)
}

func (v videoTranscode) TableName() string { return v.videoTranscodeDo.TableName() }

func (v videoTranscode) Alias() string { return v.videoTranscodeDo.Alias() }

func (v videoTranscode) Columns(cols ...field.Expr) gen.Columns {
	return v.videoTranscodeDo.Columns(cols...)
}

func (v *videoTranscode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoTranscode) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 19)
	v.fieldMap["id"] = v.ID
	v.fieldMap["user_id"] = v.UserID
	v.fieldMap["bucket_id"] = v.BucketID
	v.fieldMap["bucket_name"] = v.BucketName
	v.fieldMap["object_id"] = v.ObjectID
	v.fieldMap["object_key"] = v.ObjectKey
	v.fieldMap["object_key_hash"] = v.ObjectKeyHash
	v.fieldMap["version_id"] = v.VersionID
	v.fieldMap["source_etag"] = v.SourceEtag
	v.fieldMap["source_size"] = v.SourceSize
	v.fieldMap["status"] = v.Status
	v.fieldMap["duration_ms"] = v.DurationMs
	v.fieldMap["derived_size"] = v.DerivedSize
	v.fieldMap["profile_count"] = v.ProfileCount
	v.fieldMap["done_profile_count"] = v.DoneProfileCount
	v.fieldMap["last_error"] = v.LastError
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
	v.fieldMap["finished_at"] = v.FinishedAt
}

func (v videoTranscode) clone(db *gorm.DB) videoTranscode {
	v.videoTranscodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoTranscode) replaceDB(db *gorm.DB) videoTranscode {
	v.videoTranscodeDo.ReplaceDB(db)
	return v
}

type videoTranscodeDo struct{ gen.DO }

func (v videoTranscodeDo) Debug() *videoTranscodeDo {
	return v.withDO(v.DO.Debug())
}

func (v videoTranscodeDo) WithContext(ctx context.Context) *videoTranscodeDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoTranscodeDo) ReadDB() *videoTranscodeDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoTranscodeDo) WriteDB() *videoTranscodeDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoTranscodeDo) Session(config *gorm.Session) *videoTranscodeDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoTranscodeDo) Clauses(conds ...clause.Expression) *videoTranscodeDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoTranscodeDo) Returning(value interface{}, columns ...string) *videoTranscodeDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoTranscodeDo) Not(conds ...gen.Condition) *videoTranscodeDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoTranscodeDo) Or(conds ...gen.Condition) *videoTranscodeDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoTranscodeDo) Select(conds ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoTranscodeDo) Where(conds ...gen.Condition) *videoTranscodeDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoTranscodeDo) Order(conds ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoTranscodeDo) Distinct(cols ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoTranscodeDo) Omit(cols ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoTranscodeDo) Join(table schema.Tabler, on ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoTranscodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoTranscodeDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoTranscodeDo) Group(cols ...field.Expr) *videoTranscodeDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoTranscodeDo) Having(conds ...gen.Condition) *videoTranscodeDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoTranscodeDo) Limit(limit int) *videoTranscodeDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoTranscodeDo) Offset(offset int) *videoTranscodeDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoTranscodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoTranscodeDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoTranscodeDo) Unscoped() *videoTranscodeDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoTranscodeDo) Create(values ...*model.VideoTranscode) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoTranscodeDo) CreateInBatches(values []*model.VideoTranscode, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoTranscodeDo) Save(values ...*model.VideoTranscode) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoTranscodeDo) First() (*model.VideoTranscode, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscode), nil
	}
}

func (v videoTranscodeDo) Take() (*model.VideoTranscode, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscode), nil
	}
}

func (v videoTranscodeDo) Last() (*model.VideoTranscode, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscode), nil
	}
}

func (v videoTranscodeDo) Find() ([]*model.VideoTranscode, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoTranscode), err
}

func (v videoTranscodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoTranscode, err error) {
	buf := make([]*model.VideoTranscode, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoTranscodeDo) FindInBatches(result *[]*model.VideoTranscode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoTranscodeDo) Attrs(attrs ...field.AssignExpr) *videoTranscodeDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoTranscodeDo) Assign(attrs ...field.AssignExpr) *videoTranscodeDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoTranscodeDo) Joins(fields ...field.RelationField) *videoTranscodeDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoTranscodeDo) Preload(fields ...field.RelationField) *videoTranscodeDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoTranscodeDo) FirstOrInit() (*model.VideoTranscode, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscode), nil
	}
}

func (v videoTranscodeDo) FirstOrCreate() (*model.VideoTranscode, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscode), nil
	}
}

func (v videoTranscodeDo) FindByPage(offset int, limit int) (result []*model.VideoTranscode, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoTranscodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoTranscodeDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoTranscodeDo) Delete(models ...*model.VideoTranscode) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoTranscodeDo) withDO(do gen.Dao) *videoTranscodeDo {
	v.DO = *do.(*gen.DO)
	return v
}
