// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newVideoTranscodeProfile(db *gorm.DB, opts ...gen.DOOption) videoTranscodeProfile {
	_videoTranscodeProfile := videoTranscodeProfile{}

	_videoTranscodeProfile.videoTranscodeProfileDo.UseDB(db, opts...)
	_videoTranscodeProfile.videoTranscodeProfileDo.UseModel(&model.VideoTranscodeProfile{})

	tableName := _videoTranscodeProfile.videoTranscodeProfileDo.TableName()
	_videoTranscodeProfile.ALL = field.NewAsterisk(tableName)
	_videoTranscodeProfile.ID = field.NewInt64(tableName, "id")
	_videoTranscodeProfile.TranscodeID = field.NewInt64(tableName, "transcode_id")
	_videoTranscodeProfile.Profile = field.NewString(tableName, "profile")
	_videoTranscodeProfile.Status = field.NewInt32(tableName, "status")
	_videoTranscodeProfile.VideoBitrate = field.NewString(tableName, "video_bitrate")
	_videoTranscodeProfile.AudioBitrate = field.NewString(tableName, "audio_bitrate")
	_videoTranscodeProfile.Width = field.NewInt32(tableName, "width")
	_videoTranscodeProfile.Height = field.NewInt32(tableName, "height")
	_videoTranscodeProfile.AssetPrefix = field.NewString(tableName, "asset_prefix")
	_videoTranscodeProfile.PlaylistKey = field.NewString(tableName, "playlist_key")
	_videoTranscodeProfile.Size = field.NewInt64(tableName, "size")
	_videoTranscodeProfile.SegmentCount = field.NewInt32(tableName, "segment_count")
	_videoTranscodeProfile.DurationMs = field.NewInt64(tableName, "duration_ms")
	_videoTranscodeProfile.LastError = field.NewString(tableName, "last_error")
	_videoTranscodeProfile.StartedAt = field.NewTime(tableName, "started_at")
	_videoTranscodeProfile.FinishedAt = field.NewTime(tableName, "finished_at")
	_videoTranscodeProfile.CreatedAt = field.NewTime(tableName, "created_at")
	_videoTranscodeProfile.UpdatedAt = field.NewTime(tableName, "updated_at")

	_videoTranscodeProfile.fillFieldMap()

	return _videoTranscodeProfile
}

type videoTranscodeProfile struct {
	videoTranscodeProfileDo videoTranscodeProfileDo

	ALL          field.Asterisk
	ID           field.Int64
	TranscodeID  field.Int64
	Profile      field.String // 1080p/720p/480p/360p
	Status       field.Int32  // 0=pending 1=processing 2=done 3=failed 4=deleted
	VideoBitrate field.String
	AudioBitrate field.String
	Width        field.Int32
	Height       field.Int32
	AssetPrefix  field.String
	PlaylistKey  field.String
	Size         field.Int64
	SegmentCount field.Int32
	DurationMs   field.Int64
	LastError    field.String
	StartedAt    field.Time
	FinishedAt   field.Time
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (v videoTranscodeProfile) Table(newTableName string) *videoTranscodeProfile {
	v.videoTranscodeProfileDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoTranscodeProfile) As(alias string) *videoTranscodeProfile {
	v.videoTranscodeProfileDo.DO = *(v.videoTranscodeProfileDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoTranscodeProfile) updateTableName(table string) *videoTranscodeProfile {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.TranscodeID = field.NewInt64(table, "transcode_id")
	v.Profile = field.NewString(table, "profile")
	v.Status = field.NewInt32(table, "status")
	v.VideoBitrate = field.NewString(table, "video_bitrate")
	v.AudioBitrate = field.NewString(table, "audio_bitrate")
	v.Width = field.NewInt32(table, "width")
	v.Height = field.NewInt32(table, "height")
	v.AssetPrefix = field.NewString(table, "asset_prefix")
	v.PlaylistKey = field.NewString(table, "playlist_key")
	v.Size = field.NewInt64(table, "size")
	v.SegmentCount = field.NewInt32(table, "segment_count")
	v.DurationMs = field.NewInt64(table, "duration_ms")
	v.LastError = field.NewString(table, "last_error")
	v.StartedAt = field.NewTime(table, "started_at")
	v.FinishedAt = field.NewTime(table, "finished_at")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *videoTranscodeProfile) WithContext(ctx context.Context) *videoTranscodeProfileDo {
	return v.videoTranscodeProfileDo.WithContext(ctx)
}

func (v videoTranscodeProfile) TableName() string { return v.videoTranscodeProfileDo.TableName() }

func (v videoTranscodeProfile) Alias() string { return v.videoTranscodeProfileDo.Alias() }

func (v videoTranscodeProfile) Columns(cols ...field.Expr) gen.Columns {
	return v.videoTranscodeProfileDo.Columns(cols...)
}

func (v *videoTranscodeProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoTranscodeProfile) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 18)
	v.fieldMap["id"] = v.ID
	v.fieldMap["transcode_id"] = v.TranscodeID
	v.fieldMap["profile"] = v.Profile
	v.fieldMap["status"] = v.Status
	v.fieldMap["video_bitrate"] = v.VideoBitrate
	v.fieldMap["audio_bitrate"] = v.AudioBitrate
	v.fieldMap["width"] = v.Width
	v.fieldMap["height"] = v.Height
	v.fieldMap["asset_prefix"] = v.AssetPrefix
	v.fieldMap["playlist_key"] = v.PlaylistKey
	v.fieldMap["size"] = v.Size
	v.fieldMap["segment_count"] = v.SegmentCount
	v.fieldMap["duration_ms"] = v.DurationMs
	v.fieldMap["last_error"] = v.LastError
	v.fieldMap["started_at"] = v.StartedAt
	v.fieldMap["finished_at"] = v.FinishedAt
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v videoTranscodeProfile) clone(db *gorm.DB) videoTranscodeProfile {
	v.videoTranscodeProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoTranscodeProfile) replaceDB(db *gorm.DB) videoTranscodeProfile {
	v.videoTranscodeProfileDo.ReplaceDB(db)
	return v
}

type videoTranscodeProfileDo struct{ gen.DO }

func (v videoTranscodeProfileDo) Debug() *videoTranscodeProfileDo {
	return v.withDO(v.DO.Debug())
}

func (v videoTranscodeProfileDo) WithContext(ctx context.Context) *videoTranscodeProfileDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoTranscodeProfileDo) ReadDB() *videoTranscodeProfileDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoTranscodeProfileDo) WriteDB() *videoTranscodeProfileDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoTranscodeProfileDo) Session(config *gorm.Session) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoTranscodeProfileDo) Clauses(conds ...clause.Expression) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoTranscodeProfileDo) Returning(value interface{}, columns ...string) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoTranscodeProfileDo) Not(conds ...gen.Condition) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoTranscodeProfileDo) Or(conds ...gen.Condition) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoTranscodeProfileDo) Select(conds ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoTranscodeProfileDo) Where(conds ...gen.Condition) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoTranscodeProfileDo) Order(conds ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoTranscodeProfileDo) Distinct(cols ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoTranscodeProfileDo) Omit(cols ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoTranscodeProfileDo) Join(table schema.Tabler, on ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoTranscodeProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoTranscodeProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoTranscodeProfileDo) Group(cols ...field.Expr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoTranscodeProfileDo) Having(conds ...gen.Condition) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoTranscodeProfileDo) Limit(limit int) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoTranscodeProfileDo) Offset(offset int) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoTranscodeProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoTranscodeProfileDo) Unscoped() *videoTranscodeProfileDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoTranscodeProfileDo) Create(values ...*model.VideoTranscodeProfile) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoTranscodeProfileDo) CreateInBatches(values []*model.VideoTranscodeProfile, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoTranscodeProfileDo) Save(values ...*model.VideoTranscodeProfile) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoTranscodeProfileDo) First() (*model.VideoTranscodeProfile, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscodeProfile), nil
	}
}

func (v videoTranscodeProfileDo) Take() (*model.VideoTranscodeProfile, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscodeProfile), nil
	}
}

func (v videoTranscodeProfileDo) Last() (*model.VideoTranscodeProfile, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscodeProfile), nil
	}
}

func (v videoTranscodeProfileDo) Find() ([]*model.VideoTranscodeProfile, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoTranscodeProfile), err
}

func (v videoTranscodeProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoTranscodeProfile, err error) {
	buf := make([]*model.VideoTranscodeProfile, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoTranscodeProfileDo) FindInBatches(result *[]*model.VideoTranscodeProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoTranscodeProfileDo) Attrs(attrs ...field.AssignExpr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoTranscodeProfileDo) Assign(attrs ...field.AssignExpr) *videoTranscodeProfileDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoTranscodeProfileDo) Joins(fields ...field.RelationField) *videoTranscodeProfileDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoTranscodeProfileDo) Preload(fields ...field.RelationField) *videoTranscodeProfileDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoTranscodeProfileDo) FirstOrInit() (*model.VideoTranscodeProfile, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscodeProfile), nil
	}
}

func (v videoTranscodeProfileDo) FirstOrCreate() (*model.VideoTranscodeProfile, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTranscodeProfile), nil
	}
}

func (v videoTranscodeProfileDo) FindByPage(offset int, limit int) (result []*model.VideoTranscodeProfile, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoTranscodeProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoTranscodeProfileDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoTranscodeProfileDo) Delete(models ...*model.VideoTranscodeProfile) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoTranscodeProfileDo) withDO(do gen.Dao) *videoTranscodeProfileDo {
	v.DO = *do.(*gen.DO)
	return v
}
