// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oss/adaptor/repo/model"
)

func newVideoEncryptKey(db *gorm.DB, opts ...gen.DOOption) videoEncryptKey {
	_videoEncryptKey := videoEncryptKey{}

	_videoEncryptKey.videoEncryptKeyDo.UseDB(db, opts...)
	_videoEncryptKey.videoEncryptKeyDo.UseModel(&model.VideoEncryptKey{})

	tableName := _videoEncryptKey.videoEncryptKeyDo.TableName()
	_videoEncryptKey.ALL = field.NewAsterisk(tableName)
	_videoEncryptKey.ID = field.NewInt64(tableName, "id")
	_videoEncryptKey.TranscodeID = field.NewInt64(tableName, "transcode_id")
	_videoEncryptKey.ProfileID = field.NewInt64(tableName, "profile_id")
	_videoEncryptKey.KeyID = field.NewString(tableName, "key_id")
	_videoEncryptKey.EncryptedKey = field.NewBytes(tableName, "encrypted_key")
	_videoEncryptKey.Algorithm = field.NewString(tableName, "algorithm")
	_videoEncryptKey.KeyVersion = field.NewString(tableName, "key_version")
	_videoEncryptKey.KmsKeyID = field.NewString(tableName, "kms_key_id")
	_videoEncryptKey.CreatedAt = field.NewTime(tableName, "created_at")
	_videoEncryptKey.UpdatedAt = field.NewTime(tableName, "updated_at")

	_videoEncryptKey.fillFieldMap()

	return _videoEncryptKey
}

type videoEncryptKey struct {
	videoEncryptKeyDo videoEncryptKeyDo

	ALL          field.Asterisk
	ID           field.Int64
	TranscodeID  field.Int64
	ProfileID    field.Int64
	KeyID        field.String
	EncryptedKey field.Bytes
	Algorithm    field.String
	KeyVersion   field.String
	KmsKeyID     field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (v videoEncryptKey) Table(newTableName string) *videoEncryptKey {
	v.videoEncryptKeyDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoEncryptKey) As(alias string) *videoEncryptKey {
	v.videoEncryptKeyDo.DO = *(v.videoEncryptKeyDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoEncryptKey) updateTableName(table string) *videoEncryptKey {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.TranscodeID = field.NewInt64(table, "transcode_id")
	v.ProfileID = field.NewInt64(table, "profile_id")
	v.KeyID = field.NewString(table, "key_id")
	v.EncryptedKey = field.NewBytes(table, "encrypted_key")
	v.Algorithm = field.NewString(table, "algorithm")
	v.KeyVersion = field.NewString(table, "key_version")
	v.KmsKeyID = field.NewString(table, "kms_key_id")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *videoEncryptKey) WithContext(ctx context.Context) *videoEncryptKeyDo {
	return v.videoEncryptKeyDo.WithContext(ctx)
}

func (v videoEncryptKey) TableName() string { return v.videoEncryptKeyDo.TableName() }

func (v videoEncryptKey) Alias() string { return v.videoEncryptKeyDo.Alias() }

func (v videoEncryptKey) Columns(cols ...field.Expr) gen.Columns {
	return v.videoEncryptKeyDo.Columns(cols...)
}

func (v *videoEncryptKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoEncryptKey) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 10)
	v.fieldMap["id"] = v.ID
	v.fieldMap["transcode_id"] = v.TranscodeID
	v.fieldMap["profile_id"] = v.ProfileID
	v.fieldMap["key_id"] = v.KeyID
	v.fieldMap["encrypted_key"] = v.EncryptedKey
	v.fieldMap["algorithm"] = v.Algorithm
	v.fieldMap["key_version"] = v.KeyVersion
	v.fieldMap["kms_key_id"] = v.KmsKeyID
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v videoEncryptKey) clone(db *gorm.DB) videoEncryptKey {
	v.videoEncryptKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoEncryptKey) replaceDB(db *gorm.DB) videoEncryptKey {
	v.videoEncryptKeyDo.ReplaceDB(db)
	return v
}

type videoEncryptKeyDo struct{ gen.DO }

func (v videoEncryptKeyDo) Debug() *videoEncryptKeyDo {
	return v.withDO(v.DO.Debug())
}

func (v videoEncryptKeyDo) WithContext(ctx context.Context) *videoEncryptKeyDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoEncryptKeyDo) ReadDB() *videoEncryptKeyDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoEncryptKeyDo) WriteDB() *videoEncryptKeyDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoEncryptKeyDo) Session(config *gorm.Session) *videoEncryptKeyDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoEncryptKeyDo) Clauses(conds ...clause.Expression) *videoEncryptKeyDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoEncryptKeyDo) Returning(value interface{}, columns ...string) *videoEncryptKeyDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoEncryptKeyDo) Not(conds ...gen.Condition) *videoEncryptKeyDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoEncryptKeyDo) Or(conds ...gen.Condition) *videoEncryptKeyDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoEncryptKeyDo) Select(conds ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoEncryptKeyDo) Where(conds ...gen.Condition) *videoEncryptKeyDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoEncryptKeyDo) Order(conds ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoEncryptKeyDo) Distinct(cols ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoEncryptKeyDo) Omit(cols ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoEncryptKeyDo) Join(table schema.Tabler, on ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoEncryptKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoEncryptKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoEncryptKeyDo) Group(cols ...field.Expr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoEncryptKeyDo) Having(conds ...gen.Condition) *videoEncryptKeyDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoEncryptKeyDo) Limit(limit int) *videoEncryptKeyDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoEncryptKeyDo) Offset(offset int) *videoEncryptKeyDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoEncryptKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoEncryptKeyDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoEncryptKeyDo) Unscoped() *videoEncryptKeyDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoEncryptKeyDo) Create(values ...*model.VideoEncryptKey) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoEncryptKeyDo) CreateInBatches(values []*model.VideoEncryptKey, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoEncryptKeyDo) Save(values ...*model.VideoEncryptKey) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoEncryptKeyDo) First() (*model.VideoEncryptKey, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoEncryptKey), nil
	}
}

func (v videoEncryptKeyDo) Take() (*model.VideoEncryptKey, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoEncryptKey), nil
	}
}

func (v videoEncryptKeyDo) Last() (*model.VideoEncryptKey, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoEncryptKey), nil
	}
}

func (v videoEncryptKeyDo) Find() ([]*model.VideoEncryptKey, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoEncryptKey), err
}

func (v videoEncryptKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoEncryptKey, err error) {
	buf := make([]*model.VideoEncryptKey, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoEncryptKeyDo) FindInBatches(result *[]*model.VideoEncryptKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoEncryptKeyDo) Attrs(attrs ...field.AssignExpr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoEncryptKeyDo) Assign(attrs ...field.AssignExpr) *videoEncryptKeyDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoEncryptKeyDo) Joins(fields ...field.RelationField) *videoEncryptKeyDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoEncryptKeyDo) Preload(fields ...field.RelationField) *videoEncryptKeyDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoEncryptKeyDo) FirstOrInit() (*model.VideoEncryptKey, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoEncryptKey), nil
	}
}

func (v videoEncryptKeyDo) FirstOrCreate() (*model.VideoEncryptKey, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoEncryptKey), nil
	}
}

func (v videoEncryptKeyDo) FindByPage(offset int, limit int) (result []*model.VideoEncryptKey, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoEncryptKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoEncryptKeyDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoEncryptKeyDo) Delete(models ...*model.VideoEncryptKey) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoEncryptKeyDo) withDO(do gen.Dao) *videoEncryptKeyDo {
	v.DO = *do.(*gen.DO)
	return v
}
