// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccessKey = "access_keys"

// AccessKey AccessKey 密钥表
type AccessKey struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`      // 主键
	UserID     int64      `gorm:"column:user_id;not null;comment:所属用户ID" json:"user_id"`             // 所属用户ID
	AccessKey  string     `gorm:"column:access_key;not null;comment:AK 公开标识" json:"access_key"`      // AK 公开标识
	SecretKey  string     `gorm:"column:secret_key;not null;comment:SK 加密存储(AES)" json:"secret_key"` // SK 加密存储(AES)
	Alias_     *string    `gorm:"column:alias;comment:别名/备注" json:"alias"`                           // 别名/备注
	Status     int32      `gorm:"column:status;not null;default:1;comment:1=启用 0=禁用" json:"status"`  // 1=启用 0=禁用
	Permission *string    `gorm:"column:permission;comment:细粒度权限(NULL=全部)" json:"permission"`        // 细粒度权限(NULL=全部)
	LastUsedAt *time.Time `gorm:"column:last_used_at;comment:最后使用时间" json:"last_used_at"`            // 最后使用时间
	ExpiresAt  *time.Time `gorm:"column:expires_at;comment:过期时间(NULL=永不过期)" json:"expires_at"`       // 过期时间(NULL=永不过期)
	CreatedAt  time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AccessKey's table name
func (*AccessKey) TableName() string {
	return TableNameAccessKey
}
