// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAsyncTask = "async_tasks"

// AsyncTask 异步任务表
type AsyncTask struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                            // 主键
	TaskID     string     `gorm:"column:task_id;not null;comment:任务唯一ID" json:"task_id"`                                   // 任务唯一ID
	TaskType   string     `gorm:"column:task_type;not null;comment:PHYSICAL_MERGE/TRANSCODE/IMG_PROCESS" json:"task_type"` // PHYSICAL_MERGE/TRANSCODE/IMG_PROCESS
	UploadID   *string    `gorm:"column:upload_id;comment:关联分片会话ID" json:"upload_id"`                                      // 关联分片会话ID
	ObjectID   *int64     `gorm:"column:object_id;comment:关联对象ID" json:"object_id"`                                        // 关联对象ID
	Status     int32      `gorm:"column:status;not null;comment:0=待执行 1=执行中 2=完成 3=失败" json:"status"`                      // 0=待执行 1=执行中 2=完成 3=失败
	Progress   int32      `gorm:"column:progress;not null;comment:进度 0~100" json:"progress"`                               // 进度 0~100
	Result     *string    `gorm:"column:result;comment:执行结果" json:"result"`                                                // 执行结果
	ErrorMsg   *string    `gorm:"column:error_msg;comment:失败原因" json:"error_msg"`                                          // 失败原因
	RetryCount int32      `gorm:"column:retry_count;not null;comment:已重试次数" json:"retry_count"`                            // 已重试次数
	MaxRetry   int32      `gorm:"column:max_retry;not null;default:3;comment:最大重试次数" json:"max_retry"`                     // 最大重试次数
	WorkerID   *string    `gorm:"column:worker_id;comment:处理该任务的Worker标识" json:"worker_id"`                                // 处理该任务的Worker标识
	StartedAt  *time.Time `gorm:"column:started_at;comment:开始执行时间" json:"started_at"`                                      // 开始执行时间
	FinishedAt *time.Time `gorm:"column:finished_at;comment:完成时间" json:"finished_at"`                                      // 完成时间
	CreatedAt  time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UserID     int64      `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName AsyncTask's table name
func (*AsyncTask) TableName() string {
	return TableNameAsyncTask
}
