// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBucketCorsRule = "bucket_cors_rules"

// BucketCorsRule mapped from table <bucket_cors_rules>
type BucketCorsRule struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	BucketName     string    `gorm:"column:bucket_name;not null" json:"bucket_name"`
	AllowedOrigin  string    `gorm:"column:allowed_origin;not null" json:"allowed_origin"`
	AllowedMethods string    `gorm:"column:allowed_methods;not null" json:"allowed_methods"`
	MaxAgeSeconds  int32     `gorm:"column:max_age_seconds;not null;default:600" json:"max_age_seconds"`
	Enabled        int32     `gorm:"column:enabled;not null;default:1" json:"enabled"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName BucketCorsRule's table name
func (*BucketCorsRule) TableName() string {
	return TableNameBucketCorsRule
}
