// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBucket = "buckets"

// Bucket Bucket 表
type Bucket struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                    // 主键
	UserID       int64     `gorm:"column:user_id;not null;comment:所属用户ID" json:"user_id"`                                           // 所属用户ID
	Name         string    `gorm:"column:name;not null;comment:Bucket名(全局唯一)" json:"name"`                                          // Bucket名(全局唯一)
	Region       string    `gorm:"column:region;not null;default:cn-hz;comment:所在区域" json:"region"`                                 // 所在区域
	Acl          int32     `gorm:"column:acl;not null;comment:1=私有 2=公共读 3=公共读写" json:"acl"`                                        // 1=私有 2=公共读 3=公共读写
	Versioning   int32     `gorm:"column:versioning;not null;comment:1=关闭 2=开启版本控制" json:"versioning"`                              // 1=关闭 2=开启版本控制
	Status       int32     `gorm:"column:status;not null;default:1;comment:1=正常 2=锁定 3=删除" json:"status"`                           // 1=正常 2=锁定 3=删除
	StorageClass string    `gorm:"column:storage_class;not null;default:STANDARD;comment:STANDARD/IA/ARCHIVE" json:"storage_class"` // STANDARD/IA/ARCHIVE
	ObjectCount  int64     `gorm:"column:object_count;not null;comment:对象总数" json:"object_count"`                                   // 对象总数
	StorageSize  int64     `gorm:"column:storage_size;not null;comment:存储总量(字节)" json:"storage_size"`                               // 存储总量(字节)
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Bucket's table name
func (*Bucket) TableName() string {
	return TableNameBucket
}
