// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBucketPolicy = "bucket_policies"

// BucketPolicy Bucket 权限策略头表
type BucketPolicy struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:策略ID" json:"id"`   // 策略ID
	BucketID  int64     `gorm:"column:bucket_id;not null;comment:所属BucketID" json:"bucket_id"`    // 所属BucketID
	Effect    string    `gorm:"column:effect;not null;comment:Allow / Deny" json:"effect"`        // Allow / Deny
	Name      *string   `gorm:"column:name;comment:策略名称" json:"name"`                             // 策略名称
	Status    int32     `gorm:"column:status;not null;default:1;comment:1=启用 0=禁用" json:"status"` // 1=启用 0=禁用
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName BucketPolicy's table name
func (*BucketPolicy) TableName() string {
	return TableNameBucketPolicy
}
