// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventDelivery = "event_deliveries"

// EventDelivery 事件投递记录表
type EventDelivery struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	RuleID       int64      `gorm:"column:rule_id;not null;comment:关联规则ID" json:"rule_id"`        // 关联规则ID
	EventType    string     `gorm:"column:event_type;not null;comment:事件类型" json:"event_type"`    // 事件类型
	ObjectKey    *string    `gorm:"column:object_key;comment:触发事件的对象" json:"object_key"`          // 触发事件的对象
	Payload      string     `gorm:"column:payload;not null;comment:投递内容" json:"payload"`          // 投递内容
	Status       int32      `gorm:"column:status;not null;comment:0=待投递 1=成功 2=失败" json:"status"` // 0=待投递 1=成功 2=失败
	RetryCount   int32      `gorm:"column:retry_count;not null;comment:已重试次数" json:"retry_count"` // 已重试次数
	ResponseCode *int32     `gorm:"column:response_code;comment:Webhook响应码" json:"response_code"` // Webhook响应码
	ResponseBody *string    `gorm:"column:response_body;comment:Webhook响应体" json:"response_body"` // Webhook响应体
	NextRetryAt  *time.Time `gorm:"column:next_retry_at;comment:下次重试时间" json:"next_retry_at"`     // 下次重试时间
	CreatedAt    time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName EventDelivery's table name
func (*EventDelivery) TableName() string {
	return TableNameEventDelivery
}
