// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventRule = "event_rules"

// EventRule 事件通知规则表
type EventRule struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`           // 主键
	BucketID   int64     `gorm:"column:bucket_id;not null;comment:所属BucketID" json:"bucket_id"`          // 所属BucketID
	RuleName   string    `gorm:"column:rule_name;not null;comment:规则名" json:"rule_name"`                 // 规则名
	Events     string    `gorm:"column:events;not null;comment:监听的事件类型" json:"events"`                   // 监听的事件类型
	Prefix     *string   `gorm:"column:prefix;comment:对象前缀过滤" json:"prefix"`                             // 对象前缀过滤
	Suffix     *string   `gorm:"column:suffix;comment:对象后缀过滤" json:"suffix"`                             // 对象后缀过滤
	TargetType string    `gorm:"column:target_type;not null;comment:WEBHOOK/MQ/FUNC" json:"target_type"` // WEBHOOK/MQ/FUNC
	TargetURL  *string   `gorm:"column:target_url;comment:回调地址(Webhook)" json:"target_url"`              // 回调地址(Webhook)
	Secret     *string   `gorm:"column:secret;comment:Webhook签名密钥" json:"secret"`                        // Webhook签名密钥
	Status     int32     `gorm:"column:status;not null;default:1;comment:1=启用 0=禁用" json:"status"`       // 1=启用 0=禁用
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName EventRule's table name
func (*EventRule) TableName() string {
	return TableNameEventRule
}
