// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLifecycleRule = "lifecycle_rules"

// LifecycleRule 生命周期规则表
type LifecycleRule struct {
	ID                              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                          // 主键
	BucketID                        int64     `gorm:"column:bucket_id;not null;comment:所属BucketID" json:"bucket_id"`                                                         // 所属BucketID
	RuleName                        string    `gorm:"column:rule_name;not null;comment:规则名" json:"rule_name"`                                                                // 规则名
	Status                          int32     `gorm:"column:status;not null;default:1;comment:1=启用 0=禁用" json:"status"`                                                      // 1=启用 0=禁用
	Prefix                          *string   `gorm:"column:prefix;comment:匹配对象前缀(NULL=全部)" json:"prefix"`                                                                   // 匹配对象前缀(NULL=全部)
	TransitionDays                  *int32    `gorm:"column:transition_days;comment:N天后转换存储类型" json:"transition_days"`                                                       // N天后转换存储类型
	TransitionStorageClass          *string   `gorm:"column:transition_storage_class;comment:目标存储类型 IA/ARCHIVE" json:"transition_storage_class"`                             // 目标存储类型 IA/ARCHIVE
	ExpirationDays                  *int32    `gorm:"column:expiration_days;comment:N天后删除对象" json:"expiration_days"`                                                         // N天后删除对象
	NoncurrentVersionExpirationDays *int32    `gorm:"column:noncurrent_version_expiration_days;comment:非当前版本N天后删除" json:"noncurrent_version_expiration_days"`                // 非当前版本N天后删除
	AbortIncompleteMultipartDays    int32     `gorm:"column:abort_incomplete_multipart_days;not null;default:7;comment:未完成分片上传N天后清理" json:"abort_incomplete_multipart_days"` // 未完成分片上传N天后清理
	CreatedAt                       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt                       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName LifecycleRule's table name
func (*LifecycleRule) TableName() string {
	return TableNameLifecycleRule
}
