// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMeteringDaily = "metering_daily"

// MeteringDaily 流量计量日统计表
type MeteringDaily struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                  // 主键
	UserID          int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                           // 用户ID
	BucketID        *int64    `gorm:"column:bucket_id;comment:BucketID(NULL=用户总计)" json:"bucket_id"`                 // BucketID(NULL=用户总计)
	StatDate        time.Time `gorm:"column:stat_date;not null;comment:统计日期" json:"stat_date"`                       // 统计日期
	StorageSize     int64     `gorm:"column:storage_size;not null;comment:存储量(字节)" json:"storage_size"`              // 存储量(字节)
	ObjectCount     int64     `gorm:"column:object_count;not null;comment:对象数量" json:"object_count"`                 // 对象数量
	UploadFlow      int64     `gorm:"column:upload_flow;not null;comment:上行流量(字节)" json:"upload_flow"`               // 上行流量(字节)
	DownloadFlow    int64     `gorm:"column:download_flow;not null;comment:下行流量(字节)" json:"download_flow"`           // 下行流量(字节)
	GetRequestCount int64     `gorm:"column:get_request_count;not null;comment:GET请求次数" json:"get_request_count"`    // GET请求次数
	PutRequestCount int64     `gorm:"column:put_request_count;not null;comment:PUT请求次数" json:"put_request_count"`    // PUT请求次数
	DelRequestCount int64     `gorm:"column:del_request_count;not null;comment:DELETE请求次数" json:"del_request_count"` // DELETE请求次数
}

// TableName MeteringDaily's table name
func (*MeteringDaily) TableName() string {
	return TableNameMeteringDaily
}
