// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMultipartUpload = "multipart_uploads"

// MultipartUpload 分片上传会话表
type MultipartUpload struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	UploadID      string    `gorm:"column:upload_id;not null;comment:上传会话ID(对外暴露)" json:"upload_id"`                     // 上传会话ID(对外暴露)
	BucketID      int64     `gorm:"column:bucket_id;not null;comment:所属BucketID" json:"bucket_id"`                       // 所属BucketID
	BucketName    string    `gorm:"column:bucket_name;not null;comment:Bucket名(冗余)" json:"bucket_name"`                  // Bucket名(冗余)
	ObjectKey     string    `gorm:"column:object_key;not null;comment:目标对象路径" json:"object_key"`                         // 目标对象路径
	ObjectKeyHash string    `gorm:"column:object_key_hash;not null;comment:MD5(object_key) 用于索引" json:"object_key_hash"` // MD5(object_key) 用于索引
	UserID        int64     `gorm:"column:user_id;not null;comment:发起用户ID" json:"user_id"`                               // 发起用户ID
	TotalChunk    int32     `gorm:"column:total_chunk;not null;comment:总分片数" json:"total_chunk"`                         // 总分片数
	Status        int32     `gorm:"column:status;not null;comment:0=上传中 1=合并完成(虚拟) 2=物理合并完成 3=失败 4=已取消" json:"status"`   // 0=上传中 1=合并完成(虚拟) 2=物理合并完成 3=失败 4=已取消
	StorageClass  *string   `gorm:"column:storage_class;comment:存储类型" json:"storage_class"`                              // 存储类型
	ContentType   *string   `gorm:"column:content_type;comment:MIME类型" json:"content_type"`                              // MIME类型
	Metadata      *string   `gorm:"column:metadata;comment:用户自定义元数据" json:"metadata"`                                    // 用户自定义元数据
	ExpiresAt     time.Time `gorm:"column:expires_at;not null;comment:会话过期时间(默认24h)" json:"expires_at"`                  // 会话过期时间(默认24h)
	LastActiveAt  time.Time `gorm:"column:last_active_at;not null;comment:最后活跃时间(用于ZSET score)" json:"last_active_at"`   // 最后活跃时间(用于ZSET score)
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	VersionID     string    `gorm:"column:version_id;not null" json:"version_id"`
}

// TableName MultipartUpload's table name
func (*MultipartUpload) TableName() string {
	return TableNameMultipartUpload
}
