// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMultipartPart = "multipart_parts"

// MultipartPart 分片明细表
type MultipartPart struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`             // 主键
	UploadID    string    `gorm:"column:upload_id;not null;comment:所属上传会话ID" json:"upload_id"`              // 所属上传会话ID
	PartNumber  int32     `gorm:"column:part_number;not null;comment:分片序号 1~10000" json:"part_number"`      // 分片序号 1~10000
	Size        int64     `gorm:"column:size;not null;comment:分片大小(字节)" json:"size"`                        // 分片大小(字节)
	Etag        string    `gorm:"column:etag;not null;comment:分片MD5" json:"etag"`                           // 分片MD5
	StoragePath string    `gorm:"column:storage_path;not null;comment:分片物理存储路径" json:"storage_path"`        // 分片物理存储路径
	Status      int32     `gorm:"column:status;not null;comment:0=上传中 1=已确认(虚拟合并) 2=物理合并完可删" json:"status"` // 0=上传中 1=已确认(虚拟合并) 2=物理合并完可删
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName MultipartPart's table name
func (*MultipartPart) TableName() string {
	return TableNameMultipartPart
}
