// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameObject = "objects"

// Object Object 对象版本表
type Object struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                    // 主键
	BucketID      int64          `gorm:"column:bucket_id;not null;comment:所属 Bucket ID" json:"bucket_id"`                                 // 所属 Bucket ID
	BucketName    string         `gorm:"column:bucket_name;not null;comment:Bucket 名冗余" json:"bucket_name"`                               // Bucket 名冗余
	ObjectKey     string         `gorm:"column:object_key;not null;comment:对象路径" json:"object_key"`                                       // 对象路径
	ObjectKeyHash string         `gorm:"column:object_key_hash;not null;comment:MD5(object_key)，用于索引和唯一约束" json:"object_key_hash"`        // MD5(object_key)，用于索引和唯一约束
	VersionID     string         `gorm:"column:version_id;not null;comment:版本 ID，建议每次写入都生成" json:"version_id"`                            // 版本 ID，建议每次写入都生成
	Size          int64          `gorm:"column:size;not null;comment:对象大小，delete marker 为 0" json:"size"`                                 // 对象大小，delete marker 为 0
	Etag          string         `gorm:"column:etag;not null;comment:ETag" json:"etag"`                                                   // ETag
	ContentType   *string        `gorm:"column:content_type;comment:MIME 类型" json:"content_type"`                                         // MIME 类型
	StorageClass  string         `gorm:"column:storage_class;not null;default:STANDARD;comment:STANDARD/IA/ARCHIVE" json:"storage_class"` // STANDARD/IA/ARCHIVE
	IsMultipart   int32          `gorm:"column:is_multipart;not null;comment:0=普通对象 1=分片虚拟合并对象" json:"is_multipart"`                      // 0=普通对象 1=分片虚拟合并对象
	UploadID      *string        `gorm:"column:upload_id;comment:分片上传 ID" json:"upload_id"`                                               // 分片上传 ID
	StoragePath   *string        `gorm:"column:storage_path;comment:物理存储路径，delete marker 为空" json:"storage_path"`                         // 物理存储路径，delete marker 为空
	Acl           int32          `gorm:"column:acl;not null;comment:0=继承Bucket 1=私有 2=公共读" json:"acl"`                                    // 0=继承Bucket 1=私有 2=公共读
	Metadata      *string        `gorm:"column:metadata;comment:用户自定义元数据" json:"metadata"`                                                // 用户自定义元数据
	IsLatest      int32          `gorm:"column:is_latest;not null;comment:0=历史版本 1=当前最新版本" json:"is_latest"`                              // 0=历史版本 1=当前最新版本
	Status        int32          `gorm:"column:status;not null;default:1;comment:1=正常 2=删除标记 3=永久删除" json:"status"`                       // 1=正常 2=删除标记 3=永久删除
	AccessCount   int64          `gorm:"column:access_count;not null;comment:访问次数" json:"access_count"`                                   // 访问次数
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:永久删除时间" json:"deleted_at"`                // 永久删除时间
	LatestGuard   *string        `gorm:"column:latest_guard;comment:保证同一对象只有一个 latest" json:"latest_guard"` // 保证同一对象只有一个 latest
}

// TableName Object's table name
func (*Object) TableName() string {
	return TableNameObject
}
