// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOperationLog = "operation_logs"

// OperationLog 操作审计日志表
type OperationLog struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                      // 主键
	RequestID    string    `gorm:"column:request_id;not null;comment:请求唯一ID" json:"request_id"`                       // 请求唯一ID
	UserID       *int64    `gorm:"column:user_id;comment:操作用户ID" json:"user_id"`                                      // 操作用户ID
	AccessKey    *string   `gorm:"column:access_key;comment:使用的AK" json:"access_key"`                                 // 使用的AK
	BucketID     *int64    `gorm:"column:bucket_id;comment:操作的BucketID" json:"bucket_id"`                             // 操作的BucketID
	BucketName   *string   `gorm:"column:bucket_name;comment:Bucket名(冗余)" json:"bucket_name"`                         // Bucket名(冗余)
	ObjectKey    *string   `gorm:"column:object_key;comment:操作的对象路径" json:"object_key"`                               // 操作的对象路径
	Action       string    `gorm:"column:action;not null;comment:PutObject/GetObject/DeleteObject/..." json:"action"` // PutObject/GetObject/DeleteObject/...
	Result       int32     `gorm:"column:result;not null;default:1;comment:0=失败 1=成功" json:"result"`                  // 0=失败 1=成功
	StatusCode   int32     `gorm:"column:status_code;not null;comment:HTTP状态码" json:"status_code"`                    // HTTP状态码
	ErrorCode    *string   `gorm:"column:error_code;comment:错误码" json:"error_code"`                                   // 错误码
	ClientIP     *string   `gorm:"column:client_ip;comment:客户端IP" json:"client_ip"`                                   // 客户端IP
	UserAgent    *string   `gorm:"column:user_agent;comment:User-Agent" json:"user_agent"`                            // User-Agent
	RequestSize  int64     `gorm:"column:request_size;not null;comment:请求体大小(字节)" json:"request_size"`                // 请求体大小(字节)
	ResponseSize int64     `gorm:"column:response_size;not null;comment:响应体大小(字节)" json:"response_size"`              // 响应体大小(字节)
	DurationMs   int32     `gorm:"column:duration_ms;not null;comment:耗时(毫秒)" json:"duration_ms"`                     // 耗时(毫秒)
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
