// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePolicyCondition = "policy_conditions"

// PolicyCondition 策略条件表
type PolicyCondition struct {
	ID       int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	PolicyID int64   `gorm:"column:policy_id;not null;comment:策略ID" json:"policy_id"`      // 策略ID
	Type     string  `gorm:"column:type;not null;comment:条件类型(ip/time/etc)" json:"type"`   // 条件类型(ip/time/etc)
	CondKey  *string `gorm:"column:cond_key;comment:条件键(start/end/...)" json:"cond_key"`   // 条件键(start/end/...)
	Value    string  `gorm:"column:value;not null;comment:条件值" json:"value"`               // 条件值
}

// TableName PolicyCondition's table name
func (*PolicyCondition) TableName() string {
	return TableNamePolicyCondition
}
