// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePolicyResource = "policy_resources"

// PolicyResource 策略资源表
type PolicyResource struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`          // 主键
	PolicyID int64  `gorm:"column:policy_id;not null;comment:策略ID" json:"policy_id"`               // 策略ID
	Resource string `gorm:"column:resource;not null;comment:资源路径(如 bucketName/*)" json:"resource"` // 资源路径(如 bucketName/*)
}

// TableName PolicyResource's table name
func (*PolicyResource) TableName() string {
	return TableNamePolicyResource
}
