// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePolicyAction = "policy_actions"

// PolicyAction 策略操作表
type PolicyAction struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`  // 主键
	PolicyID int64  `gorm:"column:policy_id;not null;comment:策略ID" json:"policy_id"`       // 策略ID
	Action   string `gorm:"column:action;not null;comment:操作名(如 GetObject)" json:"action"` // 操作名(如 GetObject)
}

// TableName PolicyAction's table name
func (*PolicyAction) TableName() string {
	return TableNamePolicyAction
}
