// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePolicyPrincipal = "policy_principals"

// PolicyPrincipal 策略授权主体表
type PolicyPrincipal struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`   // 主键
	PolicyID int64  `gorm:"column:policy_id;not null;comment:策略ID" json:"policy_id"`        // 策略ID
	Type     string `gorm:"column:type;not null;comment:主体类型(user/ak/role)" json:"type"`    // 主体类型(user/ak/role)
	Value    string `gorm:"column:value;not null;comment:主体值(如 user_id 或 ak)" json:"value"` // 主体值(如 user_id 或 ak)
}

// TableName PolicyPrincipal's table name
func (*PolicyPrincipal) TableName() string {
	return TableNamePolicyPrincipal
}
