// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePresignedURL = "presigned_urls"

// PresignedURL 预签名URL表
type PresignedURL struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	Token         string    `gorm:"column:token;not null;comment:签名Token" json:"token"`                                  // 签名Token
	BucketID      int64     `gorm:"column:bucket_id;not null;comment:所属BucketID" json:"bucket_id"`                       // 所属BucketID
	ObjectKey     string    `gorm:"column:object_key;not null;comment:目标对象路径" json:"object_key"`                         // 目标对象路径
	ObjectKeyHash string    `gorm:"column:object_key_hash;not null;comment:MD5(object_key) 用于索引" json:"object_key_hash"` // MD5(object_key) 用于索引
	Method        string    `gorm:"column:method;not null;comment:GET(下载)/PUT(上传)" json:"method"`                        // GET(下载)/PUT(上传)
	UserID        int64     `gorm:"column:user_id;not null;comment:签发用户" json:"user_id"`                                 // 签发用户
	SingleUse     int32     `gorm:"column:single_use;not null;comment:0=多次 1=单次使用" json:"single_use"`                    // 0=多次 1=单次使用
	Used          int32     `gorm:"column:used;not null;comment:是否已使用" json:"used"`                                      // 是否已使用
	ExpiresAt     time.Time `gorm:"column:expires_at;not null;comment:过期时间" json:"expires_at"`                           // 过期时间
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName PresignedURL's table name
func (*PresignedURL) TableName() string {
	return TableNamePresignedURL
}
