// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User 用户表（仅账号信息，AK/SK 认证在 access_keys 表）
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                                   // 用户ID
	Email        string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                                    // 邮箱
	Status       int32     `gorm:"column:status;not null;default:1;comment:1=正常 2=禁用 3=注销" json:"status"`                            // 1=正常 2=禁用 3=注销
	StorageQuota int64     `gorm:"column:storage_quota;not null;default:107374182400;comment:存储配额(字节) 默认100GB" json:"storage_quota"` // 存储配额(字节) 默认100GB
	StorageUsed  int64     `gorm:"column:storage_used;not null;comment:已用存储(字节)" json:"storage_used"`                                // 已用存储(字节)
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
