// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoEncryptKey = "video_encrypt_keys"

// VideoEncryptKey mapped from table <video_encrypt_keys>
type VideoEncryptKey struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TranscodeID  int64     `gorm:"column:transcode_id;not null" json:"transcode_id"`
	ProfileID    int64     `gorm:"column:profile_id;not null" json:"profile_id"`
	KeyID        string    `gorm:"column:key_id;not null" json:"key_id"`
	EncryptedKey []byte    `gorm:"column:encrypted_key;not null" json:"encrypted_key"`
	Algorithm    string    `gorm:"column:algorithm;not null;default:HLS-AES-128" json:"algorithm"`
	KeyVersion   string    `gorm:"column:key_version;not null" json:"key_version"`
	KmsKeyID     string    `gorm:"column:kms_key_id;not null" json:"kms_key_id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName VideoEncryptKey's table name
func (*VideoEncryptKey) TableName() string {
	return TableNameVideoEncryptKey
}
