// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoTranscode = "video_transcodes"

// VideoTranscode mapped from table <video_transcodes>
type VideoTranscode struct {
	ID               int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID           int64      `gorm:"column:user_id;not null" json:"user_id"`
	BucketID         int64      `gorm:"column:bucket_id;not null" json:"bucket_id"`
	BucketName       string     `gorm:"column:bucket_name;not null" json:"bucket_name"`
	ObjectID         int64      `gorm:"column:object_id;not null" json:"object_id"`
	ObjectKey        string     `gorm:"column:object_key;not null" json:"object_key"`
	ObjectKeyHash    string     `gorm:"column:object_key_hash;not null" json:"object_key_hash"`
	VersionID        string     `gorm:"column:version_id;not null" json:"version_id"`
	SourceEtag       string     `gorm:"column:source_etag;not null" json:"source_etag"`
	SourceSize       int64      `gorm:"column:source_size;not null" json:"source_size"`
	Status           int32      `gorm:"column:status;not null;comment:0=pending 1=processing 2=done 3=failed 4=deleted" json:"status"` // 0=pending 1=processing 2=done 3=failed 4=deleted
	DurationMs       int64      `gorm:"column:duration_ms;not null" json:"duration_ms"`
	DerivedSize      int64      `gorm:"column:derived_size;not null" json:"derived_size"`
	ProfileCount     int32      `gorm:"column:profile_count;not null" json:"profile_count"`
	DoneProfileCount int32      `gorm:"column:done_profile_count;not null" json:"done_profile_count"`
	LastError        *string    `gorm:"column:last_error" json:"last_error"`
	CreatedAt        time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt        time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
	FinishedAt       *time.Time `gorm:"column:finished_at" json:"finished_at"`
}

// TableName VideoTranscode's table name
func (*VideoTranscode) TableName() string {
	return TableNameVideoTranscode
}
