// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoTranscodeProfile = "video_transcode_profiles"

// VideoTranscodeProfile mapped from table <video_transcode_profiles>
type VideoTranscodeProfile struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TranscodeID  int64      `gorm:"column:transcode_id;not null" json:"transcode_id"`
	Profile      string     `gorm:"column:profile;not null;comment:1080p/720p/480p/360p" json:"profile"`                           // 1080p/720p/480p/360p
	Status       int32      `gorm:"column:status;not null;comment:0=pending 1=processing 2=done 3=failed 4=deleted" json:"status"` // 0=pending 1=processing 2=done 3=failed 4=deleted
	VideoBitrate string     `gorm:"column:video_bitrate;not null" json:"video_bitrate"`
	AudioBitrate string     `gorm:"column:audio_bitrate;not null" json:"audio_bitrate"`
	Width        int32      `gorm:"column:width;not null" json:"width"`
	Fps          int32      `gorm:"column:fps;not null" json:"fps"`
	Height       int32      `gorm:"column:height;not null;default:0000000000" json:"height"`
	AssetPrefix  string     `gorm:"column:asset_prefix;not null" json:"asset_prefix"`
	PlaylistKey  string     `gorm:"column:playlist_key;not null" json:"playlist_key"`
	Size         int64      `gorm:"column:size;not null" json:"size"`
	SegmentCount int32      `gorm:"column:segment_count;not null" json:"segment_count"`
	DurationMs   int64      `gorm:"column:duration_ms;not null" json:"duration_ms"`
	LastError    *string    `gorm:"column:last_error" json:"last_error"`
	StartedAt    *time.Time `gorm:"column:started_at" json:"started_at"`
	FinishedAt   *time.Time `gorm:"column:finished_at" json:"finished_at"`
	CreatedAt    time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName VideoTranscodeProfile's table name
func (*VideoTranscodeProfile) TableName() string {
	return TableNameVideoTranscodeProfile
}
